// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assignments.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAssignment = `-- name: CreateAssignment :one
INSERT INTO assignments (class_id, title, description, due_date, max_score)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, class_id, title, description, due_date, max_score, created_at
`

type CreateAssignmentParams struct {
	ClassID     uuid.UUID          `json:"class_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	MaxScore    int32              `json:"max_score"`
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, createAssignment,
		arg.ClassID,
		arg.Title,
		arg.Description,
		arg.DueDate,
		arg.MaxScore,
	)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.Title,
		&i.Description,
		&i.DueDate,
		&i.MaxScore,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAssignment = `-- name: DeleteAssignment :exec
DELETE FROM assignments
WHERE id = $1
`

func (q *Queries) DeleteAssignment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAssignment, id)
	return err
}

const getAssignmentByID = `-- name: GetAssignmentByID :one
SELECT id, class_id, title, description, due_date, max_score, created_at
FROM assignments
WHERE id = $1
`

func (q *Queries) GetAssignmentByID(ctx context.Context, id uuid.UUID) (Assignment, error) {
	row := q.db.QueryRow(ctx, getAssignmentByID, id)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.Title,
		&i.Description,
		&i.DueDate,
		&i.MaxScore,
		&i.CreatedAt,
	)
	return i, err
}

const listAssignmentsByClassID = `-- name: ListAssignmentsByClassID :many
SELECT id, class_id, title, description, due_date, max_score, created_at
FROM assignments
WHERE class_id = $1
ORDER BY due_date ASC
`

func (q *Queries) ListAssignmentsByClassID(ctx context.Context, classID uuid.UUID) ([]Assignment, error) {
	rows, err := q.db.Query(ctx, listAssignmentsByClassID, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Assignment{}
	for rows.Next() {
		var i Assignment
		if err := rows.Scan(
			&i.ID,
			&i.ClassID,
			&i.Title,
			&i.Description,
			&i.DueDate,
			&i.MaxScore,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingAssignmentsByStudentID = `-- name: ListPendingAssignmentsByStudentID :many
SELECT 
    a.id,
    a.class_id,
    c.name AS class_name,
    a.title,
    a.description,
    a.due_date,
    a.max_score,
    a.created_at
FROM assignments a
JOIN classes c ON a.class_id = c.id
JOIN class_enrollments ce ON ce.class_id = c.id
LEFT JOIN submissions s ON s.assignment_id = a.id AND s.student_id = ce.student_id
WHERE ce.student_id = $1 
  AND s.id IS NULL
ORDER BY a.due_date ASC
`

type ListPendingAssignmentsByStudentIDRow struct {
	ID          uuid.UUID          `json:"id"`
	ClassID     uuid.UUID          `json:"class_id"`
	ClassName   string             `json:"class_name"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	MaxScore    int32              `json:"max_score"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPendingAssignmentsByStudentID(ctx context.Context, studentID uuid.UUID) ([]ListPendingAssignmentsByStudentIDRow, error) {
	rows, err := q.db.Query(ctx, listPendingAssignmentsByStudentID, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingAssignmentsByStudentIDRow{}
	for rows.Next() {
		var i ListPendingAssignmentsByStudentIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ClassID,
			&i.ClassName,
			&i.Title,
			&i.Description,
			&i.DueDate,
			&i.MaxScore,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
