// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attendance.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getClassAttendanceRoster = `-- name: GetClassAttendanceRoster :many
SELECT 
    u.id AS student_id,
    u.full_name AS student_name,
    u.email AS student_email,
    ar.id AS attendance_id,
    COALESCE(ar.status, 'unrecorded')::text AS status,
    COALESCE(ar.notes, '')::text AS notes,
    ar.date
FROM class_enrollments ce
JOIN users u ON ce.student_id = u.id
LEFT JOIN attendance_records ar 
    ON ce.class_id = ar.class_id 
    AND ce.student_id = ar.student_id 
    AND ar.date = $2::date
WHERE ce.class_id = $1
ORDER BY u.full_name ASC
`

type GetClassAttendanceRosterParams struct {
	ClassID uuid.UUID   `json:"class_id"`
	Date    pgtype.Date `json:"date"`
}

type GetClassAttendanceRosterRow struct {
	StudentID    uuid.UUID   `json:"student_id"`
	StudentName  string      `json:"student_name"`
	StudentEmail string      `json:"student_email"`
	AttendanceID pgtype.UUID `json:"attendance_id"`
	Status       string      `json:"status"`
	Notes        string      `json:"notes"`
	Date         pgtype.Date `json:"date"`
}

func (q *Queries) GetClassAttendanceRoster(ctx context.Context, arg GetClassAttendanceRosterParams) ([]GetClassAttendanceRosterRow, error) {
	rows, err := q.db.Query(ctx, getClassAttendanceRoster, arg.ClassID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetClassAttendanceRosterRow{}
	for rows.Next() {
		var i GetClassAttendanceRosterRow
		if err := rows.Scan(
			&i.StudentID,
			&i.StudentName,
			&i.StudentEmail,
			&i.AttendanceID,
			&i.Status,
			&i.Notes,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentAttendanceSummary = `-- name: GetStudentAttendanceSummary :many
SELECT 
    status,
    COUNT(*)::bigint AS count
FROM attendance_records
WHERE student_id = $1
GROUP BY status
`

type GetStudentAttendanceSummaryRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) GetStudentAttendanceSummary(ctx context.Context, studentID uuid.UUID) ([]GetStudentAttendanceSummaryRow, error) {
	rows, err := q.db.Query(ctx, getStudentAttendanceSummary, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStudentAttendanceSummaryRow{}
	for rows.Next() {
		var i GetStudentAttendanceSummaryRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendanceByClassAndDate = `-- name: ListAttendanceByClassAndDate :many
SELECT ar.id, ar.class_id, ar.student_id, u.full_name AS student_name, ar.date, ar.status, ar.notes, ar.created_at
FROM attendance_records ar
JOIN users u ON ar.student_id = u.id
WHERE ar.class_id = $1 AND ar.date = $2
ORDER BY u.full_name ASC
`

type ListAttendanceByClassAndDateParams struct {
	ClassID uuid.UUID   `json:"class_id"`
	Date    pgtype.Date `json:"date"`
}

type ListAttendanceByClassAndDateRow struct {
	ID          uuid.UUID          `json:"id"`
	ClassID     uuid.UUID          `json:"class_id"`
	StudentID   uuid.UUID          `json:"student_id"`
	StudentName string             `json:"student_name"`
	Date        pgtype.Date        `json:"date"`
	Status      string             `json:"status"`
	Notes       string             `json:"notes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAttendanceByClassAndDate(ctx context.Context, arg ListAttendanceByClassAndDateParams) ([]ListAttendanceByClassAndDateRow, error) {
	rows, err := q.db.Query(ctx, listAttendanceByClassAndDate, arg.ClassID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttendanceByClassAndDateRow{}
	for rows.Next() {
		var i ListAttendanceByClassAndDateRow
		if err := rows.Scan(
			&i.ID,
			&i.ClassID,
			&i.StudentID,
			&i.StudentName,
			&i.Date,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendanceByStudentID = `-- name: ListAttendanceByStudentID :many
SELECT ar.id, ar.class_id, c.name AS class_name, ar.date, ar.status, ar.notes, ar.created_at
FROM attendance_records ar
JOIN classes c ON ar.class_id = c.id
WHERE ar.student_id = $1
ORDER BY ar.date DESC
`

type ListAttendanceByStudentIDRow struct {
	ID        uuid.UUID          `json:"id"`
	ClassID   uuid.UUID          `json:"class_id"`
	ClassName string             `json:"class_name"`
	Date      pgtype.Date        `json:"date"`
	Status    string             `json:"status"`
	Notes     string             `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAttendanceByStudentID(ctx context.Context, studentID uuid.UUID) ([]ListAttendanceByStudentIDRow, error) {
	rows, err := q.db.Query(ctx, listAttendanceByStudentID, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttendanceByStudentIDRow{}
	for rows.Next() {
		var i ListAttendanceByStudentIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ClassID,
			&i.ClassName,
			&i.Date,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAttendance = `-- name: UpsertAttendance :one
INSERT INTO attendance_records (class_id, student_id, date, status, notes)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (class_id, student_id, date)
DO UPDATE SET
    status = EXCLUDED.status,
    notes = EXCLUDED.notes
RETURNING id, class_id, student_id, date, status, notes, created_at
`

type UpsertAttendanceParams struct {
	ClassID   uuid.UUID   `json:"class_id"`
	StudentID uuid.UUID   `json:"student_id"`
	Date      pgtype.Date `json:"date"`
	Status    string      `json:"status"`
	Notes     string      `json:"notes"`
}

func (q *Queries) UpsertAttendance(ctx context.Context, arg UpsertAttendanceParams) (AttendanceRecord, error) {
	row := q.db.QueryRow(ctx, upsertAttendance,
		arg.ClassID,
		arg.StudentID,
		arg.Date,
		arg.Status,
		arg.Notes,
	)
	var i AttendanceRecord
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.StudentID,
		&i.Date,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
