// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: classes.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const countClassesBySchool = `-- name: CountClassesBySchool :one
SELECT COUNT(*)::bigint AS total_classes
FROM classes
WHERE school_id = $1
`

func (q *Queries) CountClassesBySchool(ctx context.Context, schoolID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countClassesBySchool, schoolID)
	var total_classes int64
	err := row.Scan(&total_classes)
	return total_classes, err
}

const createClass = `-- name: CreateClass :one
INSERT INTO classes (name, grade_level, teacher_id, academic_year, school_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, grade_level, teacher_id, academic_year, created_at, school_id
`

type CreateClassParams struct {
	Name         string    `json:"name"`
	GradeLevel   string    `json:"grade_level"`
	TeacherID    uuid.UUID `json:"teacher_id"`
	AcademicYear string    `json:"academic_year"`
	SchoolID     uuid.UUID `json:"school_id"`
}

func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) (Class, error) {
	row := q.db.QueryRow(ctx, createClass,
		arg.Name,
		arg.GradeLevel,
		arg.TeacherID,
		arg.AcademicYear,
		arg.SchoolID,
	)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GradeLevel,
		&i.TeacherID,
		&i.AcademicYear,
		&i.CreatedAt,
		&i.SchoolID,
	)
	return i, err
}

const deleteClass = `-- name: DeleteClass :exec
DELETE FROM classes
WHERE id = $1
`

func (q *Queries) DeleteClass(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteClass, id)
	return err
}

const getClassByID = `-- name: GetClassByID :one
SELECT id, name, grade_level, teacher_id, academic_year, created_at, school_id
FROM classes
WHERE id = $1
`

func (q *Queries) GetClassByID(ctx context.Context, id uuid.UUID) (Class, error) {
	row := q.db.QueryRow(ctx, getClassByID, id)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GradeLevel,
		&i.TeacherID,
		&i.AcademicYear,
		&i.CreatedAt,
		&i.SchoolID,
	)
	return i, err
}

const listClasses = `-- name: ListClasses :many
SELECT id, name, grade_level, teacher_id, academic_year, created_at, school_id
FROM classes
ORDER BY name ASC
`

func (q *Queries) ListClasses(ctx context.Context) ([]Class, error) {
	rows, err := q.db.Query(ctx, listClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Class{}
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GradeLevel,
			&i.TeacherID,
			&i.AcademicYear,
			&i.CreatedAt,
			&i.SchoolID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassesBySchool = `-- name: ListClassesBySchool :many
SELECT id, name, grade_level, teacher_id, academic_year, created_at, school_id
FROM classes
WHERE school_id = $1
ORDER BY name ASC
`

func (q *Queries) ListClassesBySchool(ctx context.Context, schoolID uuid.UUID) ([]Class, error) {
	rows, err := q.db.Query(ctx, listClassesBySchool, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Class{}
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GradeLevel,
			&i.TeacherID,
			&i.AcademicYear,
			&i.CreatedAt,
			&i.SchoolID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassesByTeacher = `-- name: ListClassesByTeacher :many
SELECT id, name, grade_level, teacher_id, academic_year, created_at, school_id
FROM classes
WHERE teacher_id = $1
ORDER BY name ASC
`

func (q *Queries) ListClassesByTeacher(ctx context.Context, teacherID uuid.UUID) ([]Class, error) {
	rows, err := q.db.Query(ctx, listClassesByTeacher, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Class{}
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GradeLevel,
			&i.TeacherID,
			&i.AcademicYear,
			&i.CreatedAt,
			&i.SchoolID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClass = `-- name: UpdateClass :one
UPDATE classes
SET name = COALESCE($2, name),
    grade_level = COALESCE($3, grade_level),
    academic_year = COALESCE($4, academic_year)
WHERE id = $1
RETURNING id, name, grade_level, teacher_id, academic_year, created_at, school_id
`

type UpdateClassParams struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	GradeLevel   string    `json:"grade_level"`
	AcademicYear string    `json:"academic_year"`
}

func (q *Queries) UpdateClass(ctx context.Context, arg UpdateClassParams) (Class, error) {
	row := q.db.QueryRow(ctx, updateClass,
		arg.ID,
		arg.Name,
		arg.GradeLevel,
		arg.AcademicYear,
	)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GradeLevel,
		&i.TeacherID,
		&i.AcademicYear,
		&i.CreatedAt,
		&i.SchoolID,
	)
	return i, err
}
