// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: credentials.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAnchorBatch = `-- name: CreateAnchorBatch :one
INSERT INTO anchor_batches (
    merkle_root,
    batch_size,
    network,
    contract_address,
    tx_hash,
    block_number,
    anchored_by,
    status,
    anchored_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, merkle_root, batch_size, network, contract_address, tx_hash, block_number, anchored_by, status, created_at, anchored_at
`

type CreateAnchorBatchParams struct {
	MerkleRoot      string             `json:"merkle_root"`
	BatchSize       int32              `json:"batch_size"`
	Network         string             `json:"network"`
	ContractAddress pgtype.Text        `json:"contract_address"`
	TxHash          pgtype.Text        `json:"tx_hash"`
	BlockNumber     pgtype.Int8        `json:"block_number"`
	AnchoredBy      pgtype.UUID        `json:"anchored_by"`
	Status          string             `json:"status"`
	AnchoredAt      pgtype.Timestamptz `json:"anchored_at"`
}

func (q *Queries) CreateAnchorBatch(ctx context.Context, arg CreateAnchorBatchParams) (AnchorBatch, error) {
	row := q.db.QueryRow(ctx, createAnchorBatch,
		arg.MerkleRoot,
		arg.BatchSize,
		arg.Network,
		arg.ContractAddress,
		arg.TxHash,
		arg.BlockNumber,
		arg.AnchoredBy,
		arg.Status,
		arg.AnchoredAt,
	)
	var i AnchorBatch
	err := row.Scan(
		&i.ID,
		&i.MerkleRoot,
		&i.BatchSize,
		&i.Network,
		&i.ContractAddress,
		&i.TxHash,
		&i.BlockNumber,
		&i.AnchoredBy,
		&i.Status,
		&i.CreatedAt,
		&i.AnchoredAt,
	)
	return i, err
}

const createVerifiableCredential = `-- name: CreateVerifiableCredential :one
INSERT INTO verifiable_credentials (
    student_id,
    issuer_school_id,
    did,
    credential_type,
    credential_hash,
    merkle_root,
    merkle_proof,
    polygon_tx_hash,
    polygon_block_number,
    raw_credential_json,
    signature
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, student_id, issuer_school_id, did, credential_type, credential_hash, merkle_root, merkle_proof, polygon_tx_hash, polygon_block_number, raw_credential_json, signature, is_revoked, revocation_reason, issued_at
`

type CreateVerifiableCredentialParams struct {
	StudentID          uuid.UUID   `json:"student_id"`
	IssuerSchoolID     pgtype.UUID `json:"issuer_school_id"`
	Did                string      `json:"did"`
	CredentialType     string      `json:"credential_type"`
	CredentialHash     string      `json:"credential_hash"`
	MerkleRoot         pgtype.Text `json:"merkle_root"`
	MerkleProof        []byte      `json:"merkle_proof"`
	PolygonTxHash      pgtype.Text `json:"polygon_tx_hash"`
	PolygonBlockNumber pgtype.Int8 `json:"polygon_block_number"`
	RawCredentialJson  []byte      `json:"raw_credential_json"`
	Signature          string      `json:"signature"`
}

func (q *Queries) CreateVerifiableCredential(ctx context.Context, arg CreateVerifiableCredentialParams) (VerifiableCredential, error) {
	row := q.db.QueryRow(ctx, createVerifiableCredential,
		arg.StudentID,
		arg.IssuerSchoolID,
		arg.Did,
		arg.CredentialType,
		arg.CredentialHash,
		arg.MerkleRoot,
		arg.MerkleProof,
		arg.PolygonTxHash,
		arg.PolygonBlockNumber,
		arg.RawCredentialJson,
		arg.Signature,
	)
	var i VerifiableCredential
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.IssuerSchoolID,
		&i.Did,
		&i.CredentialType,
		&i.CredentialHash,
		&i.MerkleRoot,
		&i.MerkleProof,
		&i.PolygonTxHash,
		&i.PolygonBlockNumber,
		&i.RawCredentialJson,
		&i.Signature,
		&i.IsRevoked,
		&i.RevocationReason,
		&i.IssuedAt,
	)
	return i, err
}

const getAnchorBatchByRoot = `-- name: GetAnchorBatchByRoot :one
SELECT id, merkle_root, batch_size, network, contract_address, tx_hash, block_number, anchored_by, status, created_at, anchored_at FROM anchor_batches
WHERE merkle_root = $1
LIMIT 1
`

func (q *Queries) GetAnchorBatchByRoot(ctx context.Context, merkleRoot string) (AnchorBatch, error) {
	row := q.db.QueryRow(ctx, getAnchorBatchByRoot, merkleRoot)
	var i AnchorBatch
	err := row.Scan(
		&i.ID,
		&i.MerkleRoot,
		&i.BatchSize,
		&i.Network,
		&i.ContractAddress,
		&i.TxHash,
		&i.BlockNumber,
		&i.AnchoredBy,
		&i.Status,
		&i.CreatedAt,
		&i.AnchoredAt,
	)
	return i, err
}

const getVerifiableCredentialByDID = `-- name: GetVerifiableCredentialByDID :one
SELECT id, student_id, issuer_school_id, did, credential_type, credential_hash, merkle_root, merkle_proof, polygon_tx_hash, polygon_block_number, raw_credential_json, signature, is_revoked, revocation_reason, issued_at FROM verifiable_credentials
WHERE did = $1 AND is_revoked = FALSE
ORDER BY issued_at DESC
LIMIT 1
`

func (q *Queries) GetVerifiableCredentialByDID(ctx context.Context, did string) (VerifiableCredential, error) {
	row := q.db.QueryRow(ctx, getVerifiableCredentialByDID, did)
	var i VerifiableCredential
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.IssuerSchoolID,
		&i.Did,
		&i.CredentialType,
		&i.CredentialHash,
		&i.MerkleRoot,
		&i.MerkleProof,
		&i.PolygonTxHash,
		&i.PolygonBlockNumber,
		&i.RawCredentialJson,
		&i.Signature,
		&i.IsRevoked,
		&i.RevocationReason,
		&i.IssuedAt,
	)
	return i, err
}

const getVerifiableCredentialByHash = `-- name: GetVerifiableCredentialByHash :one
SELECT id, student_id, issuer_school_id, did, credential_type, credential_hash, merkle_root, merkle_proof, polygon_tx_hash, polygon_block_number, raw_credential_json, signature, is_revoked, revocation_reason, issued_at FROM verifiable_credentials
WHERE credential_hash = $1
LIMIT 1
`

func (q *Queries) GetVerifiableCredentialByHash(ctx context.Context, credentialHash string) (VerifiableCredential, error) {
	row := q.db.QueryRow(ctx, getVerifiableCredentialByHash, credentialHash)
	var i VerifiableCredential
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.IssuerSchoolID,
		&i.Did,
		&i.CredentialType,
		&i.CredentialHash,
		&i.MerkleRoot,
		&i.MerkleProof,
		&i.PolygonTxHash,
		&i.PolygonBlockNumber,
		&i.RawCredentialJson,
		&i.Signature,
		&i.IsRevoked,
		&i.RevocationReason,
		&i.IssuedAt,
	)
	return i, err
}

const getVerifiableCredentialByStudentID = `-- name: GetVerifiableCredentialByStudentID :one
SELECT id, student_id, issuer_school_id, did, credential_type, credential_hash, merkle_root, merkle_proof, polygon_tx_hash, polygon_block_number, raw_credential_json, signature, is_revoked, revocation_reason, issued_at FROM verifiable_credentials
WHERE student_id = $1 AND is_revoked = FALSE
ORDER BY issued_at DESC
LIMIT 1
`

func (q *Queries) GetVerifiableCredentialByStudentID(ctx context.Context, studentID uuid.UUID) (VerifiableCredential, error) {
	row := q.db.QueryRow(ctx, getVerifiableCredentialByStudentID, studentID)
	var i VerifiableCredential
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.IssuerSchoolID,
		&i.Did,
		&i.CredentialType,
		&i.CredentialHash,
		&i.MerkleRoot,
		&i.MerkleProof,
		&i.PolygonTxHash,
		&i.PolygonBlockNumber,
		&i.RawCredentialJson,
		&i.Signature,
		&i.IsRevoked,
		&i.RevocationReason,
		&i.IssuedAt,
	)
	return i, err
}

const listAnchorBatches = `-- name: ListAnchorBatches :many
SELECT id, merkle_root, batch_size, network, contract_address, tx_hash, block_number, anchored_by, status, created_at, anchored_at FROM anchor_batches
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListAnchorBatches(ctx context.Context, limit int32) ([]AnchorBatch, error) {
	rows, err := q.db.Query(ctx, listAnchorBatches, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnchorBatch{}
	for rows.Next() {
		var i AnchorBatch
		if err := rows.Scan(
			&i.ID,
			&i.MerkleRoot,
			&i.BatchSize,
			&i.Network,
			&i.ContractAddress,
			&i.TxHash,
			&i.BlockNumber,
			&i.AnchoredBy,
			&i.Status,
			&i.CreatedAt,
			&i.AnchoredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnanchoredCredentials = `-- name: ListUnanchoredCredentials :many
SELECT id, student_id, issuer_school_id, did, credential_type, credential_hash, merkle_root, merkle_proof, polygon_tx_hash, polygon_block_number, raw_credential_json, signature, is_revoked, revocation_reason, issued_at FROM verifiable_credentials
WHERE merkle_root IS NULL AND is_revoked = FALSE
ORDER BY issued_at ASC
`

func (q *Queries) ListUnanchoredCredentials(ctx context.Context) ([]VerifiableCredential, error) {
	rows, err := q.db.Query(ctx, listUnanchoredCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VerifiableCredential{}
	for rows.Next() {
		var i VerifiableCredential
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.IssuerSchoolID,
			&i.Did,
			&i.CredentialType,
			&i.CredentialHash,
			&i.MerkleRoot,
			&i.MerkleProof,
			&i.PolygonTxHash,
			&i.PolygonBlockNumber,
			&i.RawCredentialJson,
			&i.Signature,
			&i.IsRevoked,
			&i.RevocationReason,
			&i.IssuedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeCredential = `-- name: RevokeCredential :exec
UPDATE verifiable_credentials
SET is_revoked = TRUE,
    revocation_reason = $2
WHERE credential_hash = $1
`

type RevokeCredentialParams struct {
	CredentialHash   string      `json:"credential_hash"`
	RevocationReason pgtype.Text `json:"revocation_reason"`
}

func (q *Queries) RevokeCredential(ctx context.Context, arg RevokeCredentialParams) error {
	_, err := q.db.Exec(ctx, revokeCredential, arg.CredentialHash, arg.RevocationReason)
	return err
}

const updateCredentialAnchor = `-- name: UpdateCredentialAnchor :exec
UPDATE verifiable_credentials
SET merkle_root = $2,
    merkle_proof = $3,
    polygon_tx_hash = $4,
    polygon_block_number = $5
WHERE id = $1
`

type UpdateCredentialAnchorParams struct {
	ID                 uuid.UUID   `json:"id"`
	MerkleRoot         pgtype.Text `json:"merkle_root"`
	MerkleProof        []byte      `json:"merkle_proof"`
	PolygonTxHash      pgtype.Text `json:"polygon_tx_hash"`
	PolygonBlockNumber pgtype.Int8 `json:"polygon_block_number"`
}

func (q *Queries) UpdateCredentialAnchor(ctx context.Context, arg UpdateCredentialAnchorParams) error {
	_, err := q.db.Exec(ctx, updateCredentialAnchor,
		arg.ID,
		arg.MerkleRoot,
		arg.MerkleProof,
		arg.PolygonTxHash,
		arg.PolygonBlockNumber,
	)
	return err
}

const updateUserAnchorStatus = `-- name: UpdateUserAnchorStatus :exec
UPDATE users
SET anchor_status = $2,
    merkle_root = $3,
    blockchain_tx_hash = $4
WHERE id = $1
`

type UpdateUserAnchorStatusParams struct {
	ID               uuid.UUID   `json:"id"`
	AnchorStatus     pgtype.Text `json:"anchor_status"`
	MerkleRoot       pgtype.Text `json:"merkle_root"`
	BlockchainTxHash pgtype.Text `json:"blockchain_tx_hash"`
}

func (q *Queries) UpdateUserAnchorStatus(ctx context.Context, arg UpdateUserAnchorStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserAnchorStatus,
		arg.ID,
		arg.AnchorStatus,
		arg.MerkleRoot,
		arg.BlockchainTxHash,
	)
	return err
}

const updateUserBlockchainIdentity = `-- name: UpdateUserBlockchainIdentity :exec
UPDATE users
SET did = $2,
    blockchain_address = $3,
    public_key = $4,
    credential_hash = $5,
    anchor_status = $6
WHERE id = $1
`

type UpdateUserBlockchainIdentityParams struct {
	ID                uuid.UUID   `json:"id"`
	Did               pgtype.Text `json:"did"`
	BlockchainAddress pgtype.Text `json:"blockchain_address"`
	PublicKey         pgtype.Text `json:"public_key"`
	CredentialHash    pgtype.Text `json:"credential_hash"`
	AnchorStatus      pgtype.Text `json:"anchor_status"`
}

func (q *Queries) UpdateUserBlockchainIdentity(ctx context.Context, arg UpdateUserBlockchainIdentityParams) error {
	_, err := q.db.Exec(ctx, updateUserBlockchainIdentity,
		arg.ID,
		arg.Did,
		arg.BlockchainAddress,
		arg.PublicKey,
		arg.CredentialHash,
		arg.AnchorStatus,
	)
	return err
}
