// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: enrollments.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEnrollment = `-- name: CreateEnrollment :one
INSERT INTO class_enrollments (class_id, student_id)
VALUES ($1, $2)
ON CONFLICT (class_id, student_id) DO UPDATE
SET enrolled_at = class_enrollments.enrolled_at
RETURNING id, class_id, student_id, enrolled_at
`

type CreateEnrollmentParams struct {
	ClassID   uuid.UUID `json:"class_id"`
	StudentID uuid.UUID `json:"student_id"`
}

func (q *Queries) CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) (ClassEnrollment, error) {
	row := q.db.QueryRow(ctx, createEnrollment, arg.ClassID, arg.StudentID)
	var i ClassEnrollment
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.StudentID,
		&i.EnrolledAt,
	)
	return i, err
}

const deleteEnrollment = `-- name: DeleteEnrollment :exec
DELETE FROM class_enrollments
WHERE class_id = $1 AND student_id = $2
`

type DeleteEnrollmentParams struct {
	ClassID   uuid.UUID `json:"class_id"`
	StudentID uuid.UUID `json:"student_id"`
}

func (q *Queries) DeleteEnrollment(ctx context.Context, arg DeleteEnrollmentParams) error {
	_, err := q.db.Exec(ctx, deleteEnrollment, arg.ClassID, arg.StudentID)
	return err
}

const isStudentEnrolled = `-- name: IsStudentEnrolled :one
SELECT EXISTS (
    SELECT 1 FROM class_enrollments
    WHERE class_id = $1 AND student_id = $2
) AS enrolled
`

type IsStudentEnrolledParams struct {
	ClassID   uuid.UUID `json:"class_id"`
	StudentID uuid.UUID `json:"student_id"`
}

func (q *Queries) IsStudentEnrolled(ctx context.Context, arg IsStudentEnrolledParams) (bool, error) {
	row := q.db.QueryRow(ctx, isStudentEnrolled, arg.ClassID, arg.StudentID)
	var enrolled bool
	err := row.Scan(&enrolled)
	return enrolled, err
}

const listClassesByStudentID = `-- name: ListClassesByStudentID :many
SELECT c.id, c.name, c.grade_level, c.teacher_id, c.academic_year, c.created_at, ce.enrolled_at
FROM class_enrollments ce
JOIN classes c ON ce.class_id = c.id
WHERE ce.student_id = $1
ORDER BY c.name ASC
`

type ListClassesByStudentIDRow struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	GradeLevel   string             `json:"grade_level"`
	TeacherID    uuid.UUID          `json:"teacher_id"`
	AcademicYear string             `json:"academic_year"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	EnrolledAt   pgtype.Timestamptz `json:"enrolled_at"`
}

func (q *Queries) ListClassesByStudentID(ctx context.Context, studentID uuid.UUID) ([]ListClassesByStudentIDRow, error) {
	rows, err := q.db.Query(ctx, listClassesByStudentID, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClassesByStudentIDRow{}
	for rows.Next() {
		var i ListClassesByStudentIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GradeLevel,
			&i.TeacherID,
			&i.AcademicYear,
			&i.CreatedAt,
			&i.EnrolledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsByClassID = `-- name: ListStudentsByClassID :many
SELECT u.id, u.email, u.full_name, u.role, ce.enrolled_at
FROM class_enrollments ce
JOIN users u ON ce.student_id = u.id
WHERE ce.class_id = $1
ORDER BY u.full_name ASC
`

type ListStudentsByClassIDRow struct {
	ID         uuid.UUID          `json:"id"`
	Email      string             `json:"email"`
	FullName   string             `json:"full_name"`
	Role       string             `json:"role"`
	EnrolledAt pgtype.Timestamptz `json:"enrolled_at"`
}

func (q *Queries) ListStudentsByClassID(ctx context.Context, classID uuid.UUID) ([]ListStudentsByClassIDRow, error) {
	rows, err := q.db.Query(ctx, listStudentsByClassID, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentsByClassIDRow{}
	for rows.Next() {
		var i ListStudentsByClassIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.Role,
			&i.EnrolledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
