// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: exam_marks.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteExamMarksByClassAndExam = `-- name: DeleteExamMarksByClassAndExam :exec
DELETE FROM exam_marks
WHERE class_id = $1 AND exam_name = $2
`

type DeleteExamMarksByClassAndExamParams struct {
	ClassID  uuid.UUID `json:"class_id"`
	ExamName string    `json:"exam_name"`
}

func (q *Queries) DeleteExamMarksByClassAndExam(ctx context.Context, arg DeleteExamMarksByClassAndExamParams) error {
	_, err := q.db.Exec(ctx, deleteExamMarksByClassAndExam, arg.ClassID, arg.ExamName)
	return err
}

const getClassExamRoster = `-- name: GetClassExamRoster :many
SELECT 
    u.id AS student_id,
    u.full_name AS student_name,
    u.email AS student_email,
    em.id AS exam_mark_id,
    COALESCE(em.exam_name, $2)::varchar AS exam_name,
    COALESCE(em.academic_year, '')::varchar AS academic_year,
    em.myanmar,
    em.english,
    em.maths,
    em.phy,
    em.chem,
    em.bio,
    em.geo,
    em.his,
    em.eco,
    em.social,
    COALESCE(em.remarks, '')::text AS remarks,
    em.updated_at
FROM class_enrollments ce
JOIN users u ON ce.student_id = u.id
LEFT JOIN exam_marks em ON em.class_id = ce.class_id AND em.student_id = ce.student_id AND em.exam_name = $2
WHERE ce.class_id = $1
ORDER BY u.full_name ASC
`

type GetClassExamRosterParams struct {
	ClassID  uuid.UUID `json:"class_id"`
	ExamName string    `json:"exam_name"`
}

type GetClassExamRosterRow struct {
	StudentID    uuid.UUID          `json:"student_id"`
	StudentName  string             `json:"student_name"`
	StudentEmail string             `json:"student_email"`
	ExamMarkID   pgtype.UUID        `json:"exam_mark_id"`
	ExamName     string             `json:"exam_name"`
	AcademicYear string             `json:"academic_year"`
	Myanmar      pgtype.Numeric     `json:"myanmar"`
	English      pgtype.Numeric     `json:"english"`
	Maths        pgtype.Numeric     `json:"maths"`
	Phy          pgtype.Numeric     `json:"phy"`
	Chem         pgtype.Numeric     `json:"chem"`
	Bio          pgtype.Numeric     `json:"bio"`
	Geo          pgtype.Numeric     `json:"geo"`
	His          pgtype.Numeric     `json:"his"`
	Eco          pgtype.Numeric     `json:"eco"`
	Social       pgtype.Numeric     `json:"social"`
	Remarks      string             `json:"remarks"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetClassExamRoster(ctx context.Context, arg GetClassExamRosterParams) ([]GetClassExamRosterRow, error) {
	rows, err := q.db.Query(ctx, getClassExamRoster, arg.ClassID, arg.ExamName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetClassExamRosterRow{}
	for rows.Next() {
		var i GetClassExamRosterRow
		if err := rows.Scan(
			&i.StudentID,
			&i.StudentName,
			&i.StudentEmail,
			&i.ExamMarkID,
			&i.ExamName,
			&i.AcademicYear,
			&i.Myanmar,
			&i.English,
			&i.Maths,
			&i.Phy,
			&i.Chem,
			&i.Bio,
			&i.Geo,
			&i.His,
			&i.Eco,
			&i.Social,
			&i.Remarks,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistinctExamsByClass = `-- name: ListDistinctExamsByClass :many
SELECT 
    exam_name, 
    academic_year, 
    MAX(updated_at) AS last_updated,
    COUNT(DISTINCT student_id) AS student_count
FROM exam_marks
WHERE class_id = $1
GROUP BY exam_name, academic_year
ORDER BY last_updated DESC
`

type ListDistinctExamsByClassRow struct {
	ExamName     string      `json:"exam_name"`
	AcademicYear string      `json:"academic_year"`
	LastUpdated  interface{} `json:"last_updated"`
	StudentCount int64       `json:"student_count"`
}

func (q *Queries) ListDistinctExamsByClass(ctx context.Context, classID uuid.UUID) ([]ListDistinctExamsByClassRow, error) {
	rows, err := q.db.Query(ctx, listDistinctExamsByClass, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDistinctExamsByClassRow{}
	for rows.Next() {
		var i ListDistinctExamsByClassRow
		if err := rows.Scan(
			&i.ExamName,
			&i.AcademicYear,
			&i.LastUpdated,
			&i.StudentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertExamMark = `-- name: UpsertExamMark :one
INSERT INTO exam_marks (
    class_id,
    student_id,
    exam_name,
    academic_year,
    myanmar,
    english,
    maths,
    phy,
    chem,
    bio,
    geo,
    his,
    eco,
    social,
    remarks,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, NOW()
)
ON CONFLICT (class_id, student_id, exam_name)
DO UPDATE SET
    academic_year = EXCLUDED.academic_year,
    myanmar = EXCLUDED.myanmar,
    english = EXCLUDED.english,
    maths = EXCLUDED.maths,
    phy = EXCLUDED.phy,
    chem = EXCLUDED.chem,
    bio = EXCLUDED.bio,
    geo = EXCLUDED.geo,
    his = EXCLUDED.his,
    eco = EXCLUDED.eco,
    social = EXCLUDED.social,
    remarks = EXCLUDED.remarks,
    updated_at = NOW()
RETURNING id, class_id, student_id, exam_name, academic_year, myanmar, english, maths, phy, chem, bio, geo, his, eco, social, remarks, created_at, updated_at
`

type UpsertExamMarkParams struct {
	ClassID      uuid.UUID      `json:"class_id"`
	StudentID    uuid.UUID      `json:"student_id"`
	ExamName     string         `json:"exam_name"`
	AcademicYear string         `json:"academic_year"`
	Myanmar      pgtype.Numeric `json:"myanmar"`
	English      pgtype.Numeric `json:"english"`
	Maths        pgtype.Numeric `json:"maths"`
	Phy          pgtype.Numeric `json:"phy"`
	Chem         pgtype.Numeric `json:"chem"`
	Bio          pgtype.Numeric `json:"bio"`
	Geo          pgtype.Numeric `json:"geo"`
	His          pgtype.Numeric `json:"his"`
	Eco          pgtype.Numeric `json:"eco"`
	Social       pgtype.Numeric `json:"social"`
	Remarks      string         `json:"remarks"`
}

func (q *Queries) UpsertExamMark(ctx context.Context, arg UpsertExamMarkParams) (ExamMark, error) {
	row := q.db.QueryRow(ctx, upsertExamMark,
		arg.ClassID,
		arg.StudentID,
		arg.ExamName,
		arg.AcademicYear,
		arg.Myanmar,
		arg.English,
		arg.Maths,
		arg.Phy,
		arg.Chem,
		arg.Bio,
		arg.Geo,
		arg.His,
		arg.Eco,
		arg.Social,
		arg.Remarks,
	)
	var i ExamMark
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.StudentID,
		&i.ExamName,
		&i.AcademicYear,
		&i.Myanmar,
		&i.English,
		&i.Maths,
		&i.Phy,
		&i.Chem,
		&i.Bio,
		&i.Geo,
		&i.His,
		&i.Eco,
		&i.Social,
		&i.Remarks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
