// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: lesson_plans.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createLessonPlan = `-- name: CreateLessonPlan :one
INSERT INTO lesson_plans (teacher_id, subject, grade_level, topic, duration_minutes, generated_markdown)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, teacher_id, subject, grade_level, topic, duration_minutes, generated_markdown, created_at
`

type CreateLessonPlanParams struct {
	TeacherID         uuid.UUID `json:"teacher_id"`
	Subject           string    `json:"subject"`
	GradeLevel        string    `json:"grade_level"`
	Topic             string    `json:"topic"`
	DurationMinutes   int32     `json:"duration_minutes"`
	GeneratedMarkdown string    `json:"generated_markdown"`
}

func (q *Queries) CreateLessonPlan(ctx context.Context, arg CreateLessonPlanParams) (LessonPlan, error) {
	row := q.db.QueryRow(ctx, createLessonPlan,
		arg.TeacherID,
		arg.Subject,
		arg.GradeLevel,
		arg.Topic,
		arg.DurationMinutes,
		arg.GeneratedMarkdown,
	)
	var i LessonPlan
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Subject,
		&i.GradeLevel,
		&i.Topic,
		&i.DurationMinutes,
		&i.GeneratedMarkdown,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLessonPlan = `-- name: DeleteLessonPlan :exec
DELETE FROM lesson_plans
WHERE id = $1
`

func (q *Queries) DeleteLessonPlan(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLessonPlan, id)
	return err
}

const getLessonPlanByID = `-- name: GetLessonPlanByID :one
SELECT id, teacher_id, subject, grade_level, topic, duration_minutes, generated_markdown, created_at
FROM lesson_plans
WHERE id = $1
`

func (q *Queries) GetLessonPlanByID(ctx context.Context, id uuid.UUID) (LessonPlan, error) {
	row := q.db.QueryRow(ctx, getLessonPlanByID, id)
	var i LessonPlan
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Subject,
		&i.GradeLevel,
		&i.Topic,
		&i.DurationMinutes,
		&i.GeneratedMarkdown,
		&i.CreatedAt,
	)
	return i, err
}

const listLessonPlansByTeacherID = `-- name: ListLessonPlansByTeacherID :many
SELECT id, teacher_id, subject, grade_level, topic, duration_minutes, generated_markdown, created_at
FROM lesson_plans
WHERE teacher_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListLessonPlansByTeacherID(ctx context.Context, teacherID uuid.UUID) ([]LessonPlan, error) {
	rows, err := q.db.Query(ctx, listLessonPlansByTeacherID, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LessonPlan{}
	for rows.Next() {
		var i LessonPlan
		if err := rows.Scan(
			&i.ID,
			&i.TeacherID,
			&i.Subject,
			&i.GradeLevel,
			&i.Topic,
			&i.DurationMinutes,
			&i.GeneratedMarkdown,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
