// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lesson_plans.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLessonPlan = `-- name: CreateLessonPlan :one
INSERT INTO lesson_plans (teacher_id, school_id, subject, grade_level, topic, duration_minutes, generated_markdown, generated_markdown_burmese)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, teacher_id, subject, grade_level, topic, duration_minutes, generated_markdown, created_at, generated_markdown_burmese, rag_metadata, embedding, school_id
`

type CreateLessonPlanParams struct {
	TeacherID                uuid.UUID   `json:"teacher_id"`
	SchoolID                 pgtype.UUID `json:"school_id"`
	Subject                  string      `json:"subject"`
	GradeLevel               string      `json:"grade_level"`
	Topic                    string      `json:"topic"`
	DurationMinutes          int32       `json:"duration_minutes"`
	GeneratedMarkdown        string      `json:"generated_markdown"`
	GeneratedMarkdownBurmese string      `json:"generated_markdown_burmese"`
}

func (q *Queries) CreateLessonPlan(ctx context.Context, arg CreateLessonPlanParams) (LessonPlan, error) {
	row := q.db.QueryRow(ctx, createLessonPlan,
		arg.TeacherID,
		arg.SchoolID,
		arg.Subject,
		arg.GradeLevel,
		arg.Topic,
		arg.DurationMinutes,
		arg.GeneratedMarkdown,
		arg.GeneratedMarkdownBurmese,
	)
	var i LessonPlan
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Subject,
		&i.GradeLevel,
		&i.Topic,
		&i.DurationMinutes,
		&i.GeneratedMarkdown,
		&i.CreatedAt,
		&i.GeneratedMarkdownBurmese,
		&i.RagMetadata,
		&i.Embedding,
		&i.SchoolID,
	)
	return i, err
}

const deleteLessonPlan = `-- name: DeleteLessonPlan :exec
DELETE FROM lesson_plans
WHERE id = $1
`

func (q *Queries) DeleteLessonPlan(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLessonPlan, id)
	return err
}

const getLessonPlanByID = `-- name: GetLessonPlanByID :one
SELECT id, teacher_id, subject, grade_level, topic, duration_minutes, generated_markdown, created_at, generated_markdown_burmese, rag_metadata, embedding, school_id
FROM lesson_plans
WHERE id = $1
`

func (q *Queries) GetLessonPlanByID(ctx context.Context, id uuid.UUID) (LessonPlan, error) {
	row := q.db.QueryRow(ctx, getLessonPlanByID, id)
	var i LessonPlan
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Subject,
		&i.GradeLevel,
		&i.Topic,
		&i.DurationMinutes,
		&i.GeneratedMarkdown,
		&i.CreatedAt,
		&i.GeneratedMarkdownBurmese,
		&i.RagMetadata,
		&i.Embedding,
		&i.SchoolID,
	)
	return i, err
}

const listLessonPlansBySchoolAndGrade = `-- name: ListLessonPlansBySchoolAndGrade :many
SELECT id, teacher_id, subject, grade_level, topic, duration_minutes, generated_markdown, created_at, generated_markdown_burmese, rag_metadata, embedding, school_id
FROM lesson_plans
WHERE (school_id = $1 OR school_id IS NULL) AND grade_level = $2
ORDER BY created_at DESC
`

type ListLessonPlansBySchoolAndGradeParams struct {
	SchoolID   pgtype.UUID `json:"school_id"`
	GradeLevel string      `json:"grade_level"`
}

func (q *Queries) ListLessonPlansBySchoolAndGrade(ctx context.Context, arg ListLessonPlansBySchoolAndGradeParams) ([]LessonPlan, error) {
	rows, err := q.db.Query(ctx, listLessonPlansBySchoolAndGrade, arg.SchoolID, arg.GradeLevel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LessonPlan{}
	for rows.Next() {
		var i LessonPlan
		if err := rows.Scan(
			&i.ID,
			&i.TeacherID,
			&i.Subject,
			&i.GradeLevel,
			&i.Topic,
			&i.DurationMinutes,
			&i.GeneratedMarkdown,
			&i.CreatedAt,
			&i.GeneratedMarkdownBurmese,
			&i.RagMetadata,
			&i.Embedding,
			&i.SchoolID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonPlansBySchoolID = `-- name: ListLessonPlansBySchoolID :many
SELECT id, teacher_id, subject, grade_level, topic, duration_minutes, generated_markdown, created_at, generated_markdown_burmese, rag_metadata, embedding, school_id
FROM lesson_plans
WHERE school_id = $1 OR school_id IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListLessonPlansBySchoolID(ctx context.Context, schoolID pgtype.UUID) ([]LessonPlan, error) {
	rows, err := q.db.Query(ctx, listLessonPlansBySchoolID, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LessonPlan{}
	for rows.Next() {
		var i LessonPlan
		if err := rows.Scan(
			&i.ID,
			&i.TeacherID,
			&i.Subject,
			&i.GradeLevel,
			&i.Topic,
			&i.DurationMinutes,
			&i.GeneratedMarkdown,
			&i.CreatedAt,
			&i.GeneratedMarkdownBurmese,
			&i.RagMetadata,
			&i.Embedding,
			&i.SchoolID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLessonPlansByTeacherID = `-- name: ListLessonPlansByTeacherID :many
SELECT id, teacher_id, subject, grade_level, topic, duration_minutes, generated_markdown, created_at, generated_markdown_burmese, rag_metadata, embedding, school_id
FROM lesson_plans
WHERE teacher_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListLessonPlansByTeacherID(ctx context.Context, teacherID uuid.UUID) ([]LessonPlan, error) {
	rows, err := q.db.Query(ctx, listLessonPlansByTeacherID, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LessonPlan{}
	for rows.Next() {
		var i LessonPlan
		if err := rows.Scan(
			&i.ID,
			&i.TeacherID,
			&i.Subject,
			&i.GradeLevel,
			&i.Topic,
			&i.DurationMinutes,
			&i.GeneratedMarkdown,
			&i.CreatedAt,
			&i.GeneratedMarkdownBurmese,
			&i.RagMetadata,
			&i.Embedding,
			&i.SchoolID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLessonPlanBurmese = `-- name: UpdateLessonPlanBurmese :one
UPDATE lesson_plans
SET generated_markdown_burmese = $2
WHERE id = $1
RETURNING id, teacher_id, subject, grade_level, topic, duration_minutes, generated_markdown, created_at, generated_markdown_burmese, rag_metadata, embedding, school_id
`

type UpdateLessonPlanBurmeseParams struct {
	ID                       uuid.UUID `json:"id"`
	GeneratedMarkdownBurmese string    `json:"generated_markdown_burmese"`
}

func (q *Queries) UpdateLessonPlanBurmese(ctx context.Context, arg UpdateLessonPlanBurmeseParams) (LessonPlan, error) {
	row := q.db.QueryRow(ctx, updateLessonPlanBurmese, arg.ID, arg.GeneratedMarkdownBurmese)
	var i LessonPlan
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Subject,
		&i.GradeLevel,
		&i.Topic,
		&i.DurationMinutes,
		&i.GeneratedMarkdown,
		&i.CreatedAt,
		&i.GeneratedMarkdownBurmese,
		&i.RagMetadata,
		&i.Embedding,
		&i.SchoolID,
	)
	return i, err
}

const updateLessonPlanContent = `-- name: UpdateLessonPlanContent :one
UPDATE lesson_plans
SET topic = $2,
    duration_minutes = $3,
    generated_markdown = $4,
    generated_markdown_burmese = $5
WHERE id = $1
RETURNING id, teacher_id, subject, grade_level, topic, duration_minutes, generated_markdown, created_at, generated_markdown_burmese, rag_metadata, embedding, school_id
`

type UpdateLessonPlanContentParams struct {
	ID                       uuid.UUID `json:"id"`
	Topic                    string    `json:"topic"`
	DurationMinutes          int32     `json:"duration_minutes"`
	GeneratedMarkdown        string    `json:"generated_markdown"`
	GeneratedMarkdownBurmese string    `json:"generated_markdown_burmese"`
}

func (q *Queries) UpdateLessonPlanContent(ctx context.Context, arg UpdateLessonPlanContentParams) (LessonPlan, error) {
	row := q.db.QueryRow(ctx, updateLessonPlanContent,
		arg.ID,
		arg.Topic,
		arg.DurationMinutes,
		arg.GeneratedMarkdown,
		arg.GeneratedMarkdownBurmese,
	)
	var i LessonPlan
	err := row.Scan(
		&i.ID,
		&i.TeacherID,
		&i.Subject,
		&i.GradeLevel,
		&i.Topic,
		&i.DurationMinutes,
		&i.GeneratedMarkdown,
		&i.CreatedAt,
		&i.GeneratedMarkdownBurmese,
		&i.RagMetadata,
		&i.Embedding,
		&i.SchoolID,
	)
	return i, err
}
