// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: messaging.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*)::bigint AS unread_count
FROM notifications
WHERE user_id = $1 AND is_read = FALSE
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var unread_count int64
	err := row.Scan(&unread_count)
	return unread_count, err
}

const createAnnouncement = `-- name: CreateAnnouncement :one
INSERT INTO announcements (class_id, teacher_id, title, content, priority)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, class_id, teacher_id, title, content, priority, created_at
`

type CreateAnnouncementParams struct {
	ClassID   uuid.UUID `json:"class_id"`
	TeacherID uuid.UUID `json:"teacher_id"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	Priority  string    `json:"priority"`
}

func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, createAnnouncement,
		arg.ClassID,
		arg.TeacherID,
		arg.Title,
		arg.Content,
		arg.Priority,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.TeacherID,
		&i.Title,
		&i.Content,
		&i.Priority,
		&i.CreatedAt,
	)
	return i, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (school_id, teacher_id, parent_id, student_id, last_message_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (teacher_id, parent_id, student_id)
DO UPDATE SET last_message_at = NOW()
RETURNING id, school_id, teacher_id, parent_id, student_id, last_message_at, created_at
`

type CreateConversationParams struct {
	SchoolID  pgtype.UUID `json:"school_id"`
	TeacherID uuid.UUID   `json:"teacher_id"`
	ParentID  uuid.UUID   `json:"parent_id"`
	StudentID pgtype.UUID `json:"student_id"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation,
		arg.SchoolID,
		arg.TeacherID,
		arg.ParentID,
		arg.StudentID,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.TeacherID,
		&i.ParentID,
		&i.StudentID,
		&i.LastMessageAt,
		&i.CreatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (conversation_id, sender_id, content, is_read)
VALUES ($1, $2, $3, FALSE)
RETURNING id, conversation_id, sender_id, content, is_read, created_at
`

type CreateMessageParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	SenderID       uuid.UUID `json:"sender_id"`
	Content        string    `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ConversationID, arg.SenderID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Content,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, type, title, body, data, is_read)
VALUES ($1, $2, $3, $4, $5, FALSE)
RETURNING id, user_id, type, title, body, data, is_read, created_at
`

type CreateNotificationParams struct {
	UserID uuid.UUID `json:"user_id"`
	Type   string    `json:"type"`
	Title  string    `json:"title"`
	Body   string    `json:"body"`
	Data   []byte    `json:"data"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Data,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec
DELETE FROM user_device_tokens
WHERE fcm_token = $1
`

func (q *Queries) DeleteDeviceToken(ctx context.Context, fcmToken string) error {
	_, err := q.db.Exec(ctx, deleteDeviceToken, fcmToken)
	return err
}

const deleteUserDeviceToken = `-- name: DeleteUserDeviceToken :exec
DELETE FROM user_device_tokens
WHERE user_id = $1 AND fcm_token = $2
`

type DeleteUserDeviceTokenParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FcmToken string    `json:"fcm_token"`
}

func (q *Queries) DeleteUserDeviceToken(ctx context.Context, arg DeleteUserDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, deleteUserDeviceToken, arg.UserID, arg.FcmToken)
	return err
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT c.id, c.school_id, c.teacher_id, c.parent_id, c.student_id, c.last_message_at, c.created_at,
       t.full_name as teacher_name, t.email as teacher_email,
       p.full_name as parent_name, p.email as parent_email,
       COALESCE(s.full_name, '') as student_name
FROM conversations c
JOIN users t ON t.id = c.teacher_id
JOIN users p ON p.id = c.parent_id
LEFT JOIN users s ON s.id = c.student_id
WHERE c.id = $1
`

type GetConversationByIDRow struct {
	ID            uuid.UUID          `json:"id"`
	SchoolID      pgtype.UUID        `json:"school_id"`
	TeacherID     uuid.UUID          `json:"teacher_id"`
	ParentID      uuid.UUID          `json:"parent_id"`
	StudentID     pgtype.UUID        `json:"student_id"`
	LastMessageAt pgtype.Timestamptz `json:"last_message_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	TeacherName   string             `json:"teacher_name"`
	TeacherEmail  string             `json:"teacher_email"`
	ParentName    string             `json:"parent_name"`
	ParentEmail   string             `json:"parent_email"`
	StudentName   string             `json:"student_name"`
}

func (q *Queries) GetConversationByID(ctx context.Context, id uuid.UUID) (GetConversationByIDRow, error) {
	row := q.db.QueryRow(ctx, getConversationByID, id)
	var i GetConversationByIDRow
	err := row.Scan(
		&i.ID,
		&i.SchoolID,
		&i.TeacherID,
		&i.ParentID,
		&i.StudentID,
		&i.LastMessageAt,
		&i.CreatedAt,
		&i.TeacherName,
		&i.TeacherEmail,
		&i.ParentName,
		&i.ParentEmail,
		&i.StudentName,
	)
	return i, err
}

const getParentByStudentID = `-- name: GetParentByStudentID :one
SELECT p.id, p.email, p.full_name
FROM users s
JOIN users p ON p.id = s.parent_id
WHERE s.id = $1 AND s.parent_id IS NOT NULL
`

type GetParentByStudentIDRow struct {
	ID       uuid.UUID `json:"id"`
	Email    string    `json:"email"`
	FullName string    `json:"full_name"`
}

func (q *Queries) GetParentByStudentID(ctx context.Context, id uuid.UUID) (GetParentByStudentIDRow, error) {
	row := q.db.QueryRow(ctx, getParentByStudentID, id)
	var i GetParentByStudentIDRow
	err := row.Scan(&i.ID, &i.Email, &i.FullName)
	return i, err
}

const getTeacherByStudentID = `-- name: GetTeacherByStudentID :one
SELECT DISTINCT u.id, u.email, u.full_name, c.id as class_id, c.name as class_name
FROM class_enrollments ce
JOIN classes c ON c.id = ce.class_id
JOIN users u ON u.id = c.teacher_id
WHERE ce.student_id = $1
LIMIT 1
`

type GetTeacherByStudentIDRow struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	FullName  string    `json:"full_name"`
	ClassID   uuid.UUID `json:"class_id"`
	ClassName string    `json:"class_name"`
}

func (q *Queries) GetTeacherByStudentID(ctx context.Context, studentID uuid.UUID) (GetTeacherByStudentIDRow, error) {
	row := q.db.QueryRow(ctx, getTeacherByStudentID, studentID)
	var i GetTeacherByStudentIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.ClassID,
		&i.ClassName,
	)
	return i, err
}

const listAnnouncementsByClass = `-- name: ListAnnouncementsByClass :many
SELECT a.id, a.class_id, a.teacher_id, a.title, a.content, a.priority, a.created_at,
       u.full_name as teacher_name, c.name as class_name
FROM announcements a
JOIN users u ON u.id = a.teacher_id
JOIN classes c ON c.id = a.class_id
WHERE a.class_id = $1
ORDER BY a.created_at DESC
`

type ListAnnouncementsByClassRow struct {
	ID          uuid.UUID          `json:"id"`
	ClassID     uuid.UUID          `json:"class_id"`
	TeacherID   uuid.UUID          `json:"teacher_id"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	Priority    string             `json:"priority"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	TeacherName string             `json:"teacher_name"`
	ClassName   string             `json:"class_name"`
}

func (q *Queries) ListAnnouncementsByClass(ctx context.Context, classID uuid.UUID) ([]ListAnnouncementsByClassRow, error) {
	rows, err := q.db.Query(ctx, listAnnouncementsByClass, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnnouncementsByClassRow{}
	for rows.Next() {
		var i ListAnnouncementsByClassRow
		if err := rows.Scan(
			&i.ID,
			&i.ClassID,
			&i.TeacherID,
			&i.Title,
			&i.Content,
			&i.Priority,
			&i.CreatedAt,
			&i.TeacherName,
			&i.ClassName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnnouncementsForParent = `-- name: ListAnnouncementsForParent :many
SELECT DISTINCT a.id, a.class_id, a.teacher_id, a.title, a.content, a.priority, a.created_at,
       u.full_name as teacher_name, c.name as class_name, s.full_name as student_name
FROM announcements a
JOIN classes c ON c.id = a.class_id
JOIN users u ON u.id = a.teacher_id
JOIN class_enrollments ce ON ce.class_id = c.id
JOIN users s ON s.id = ce.student_id
WHERE s.parent_id = $1
ORDER BY a.created_at DESC
`

type ListAnnouncementsForParentRow struct {
	ID          uuid.UUID          `json:"id"`
	ClassID     uuid.UUID          `json:"class_id"`
	TeacherID   uuid.UUID          `json:"teacher_id"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	Priority    string             `json:"priority"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	TeacherName string             `json:"teacher_name"`
	ClassName   string             `json:"class_name"`
	StudentName string             `json:"student_name"`
}

func (q *Queries) ListAnnouncementsForParent(ctx context.Context, parentID pgtype.UUID) ([]ListAnnouncementsForParentRow, error) {
	rows, err := q.db.Query(ctx, listAnnouncementsForParent, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnnouncementsForParentRow{}
	for rows.Next() {
		var i ListAnnouncementsForParentRow
		if err := rows.Scan(
			&i.ID,
			&i.ClassID,
			&i.TeacherID,
			&i.Title,
			&i.Content,
			&i.Priority,
			&i.CreatedAt,
			&i.TeacherName,
			&i.ClassName,
			&i.StudentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceTokensByUserID = `-- name: ListDeviceTokensByUserID :many
SELECT id, user_id, fcm_token, platform, created_at, updated_at
FROM user_device_tokens
WHERE user_id = $1
`

func (q *Queries) ListDeviceTokensByUserID(ctx context.Context, userID uuid.UUID) ([]UserDeviceToken, error) {
	rows, err := q.db.Query(ctx, listDeviceTokensByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserDeviceToken{}
	for rows.Next() {
		var i UserDeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FcmToken,
			&i.Platform,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByConversation = `-- name: ListMessagesByConversation :many
SELECT m.id, m.conversation_id, m.sender_id, m.content, m.is_read, m.created_at,
       u.full_name as sender_name, u.role as sender_role
FROM messages m
JOIN users u ON u.id = m.sender_id
WHERE m.conversation_id = $1
ORDER BY m.created_at ASC
`

type ListMessagesByConversationRow struct {
	ID             uuid.UUID          `json:"id"`
	ConversationID uuid.UUID          `json:"conversation_id"`
	SenderID       uuid.UUID          `json:"sender_id"`
	Content        string             `json:"content"`
	IsRead         bool               `json:"is_read"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	SenderName     string             `json:"sender_name"`
	SenderRole     string             `json:"sender_role"`
}

func (q *Queries) ListMessagesByConversation(ctx context.Context, conversationID uuid.UUID) ([]ListMessagesByConversationRow, error) {
	rows, err := q.db.Query(ctx, listMessagesByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesByConversationRow{}
	for rows.Next() {
		var i ListMessagesByConversationRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Content,
			&i.IsRead,
			&i.CreatedAt,
			&i.SenderName,
			&i.SenderRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT id, user_id, type, title, body, data, is_read, created_at
FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParentsByClassID = `-- name: ListParentsByClassID :many
SELECT DISTINCT p.id, p.email, p.full_name
FROM class_enrollments ce
JOIN users s ON s.id = ce.student_id
JOIN users p ON p.id = s.parent_id
WHERE ce.class_id = $1 AND s.parent_id IS NOT NULL
`

type ListParentsByClassIDRow struct {
	ID       uuid.UUID `json:"id"`
	Email    string    `json:"email"`
	FullName string    `json:"full_name"`
}

func (q *Queries) ListParentsByClassID(ctx context.Context, classID uuid.UUID) ([]ListParentsByClassIDRow, error) {
	rows, err := q.db.Query(ctx, listParentsByClassID, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListParentsByClassIDRow{}
	for rows.Next() {
		var i ListParentsByClassIDRow
		if err := rows.Scan(&i.ID, &i.Email, &i.FullName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserConversations = `-- name: ListUserConversations :many
SELECT c.id, c.school_id, c.teacher_id, c.parent_id, c.student_id, c.last_message_at, c.created_at,
       t.full_name as teacher_name, t.email as teacher_email,
       p.full_name as parent_name, p.email as parent_email,
       COALESCE(s.full_name, '') as student_name,
       COALESCE((SELECT content FROM messages m WHERE m.conversation_id = c.id ORDER BY m.created_at DESC LIMIT 1), '')::text as latest_message_content,
       COALESCE((SELECT created_at FROM messages m WHERE m.conversation_id = c.id ORDER BY m.created_at DESC LIMIT 1), c.created_at) as latest_message_at,
       COALESCE((SELECT COUNT(*)::bigint FROM messages m WHERE m.conversation_id = c.id AND m.is_read = FALSE AND m.sender_id != $1), 0)::bigint as unread_count
FROM conversations c
JOIN users t ON t.id = c.teacher_id
JOIN users p ON p.id = c.parent_id
LEFT JOIN users s ON s.id = c.student_id
WHERE c.teacher_id = $1 OR c.parent_id = $1
ORDER BY c.last_message_at DESC
`

type ListUserConversationsRow struct {
	ID                   uuid.UUID          `json:"id"`
	SchoolID             pgtype.UUID        `json:"school_id"`
	TeacherID            uuid.UUID          `json:"teacher_id"`
	ParentID             uuid.UUID          `json:"parent_id"`
	StudentID            pgtype.UUID        `json:"student_id"`
	LastMessageAt        pgtype.Timestamptz `json:"last_message_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	TeacherName          string             `json:"teacher_name"`
	TeacherEmail         string             `json:"teacher_email"`
	ParentName           string             `json:"parent_name"`
	ParentEmail          string             `json:"parent_email"`
	StudentName          string             `json:"student_name"`
	LatestMessageContent string             `json:"latest_message_content"`
	LatestMessageAt      pgtype.Timestamptz `json:"latest_message_at"`
	UnreadCount          int64              `json:"unread_count"`
}

func (q *Queries) ListUserConversations(ctx context.Context, senderID uuid.UUID) ([]ListUserConversationsRow, error) {
	rows, err := q.db.Query(ctx, listUserConversations, senderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserConversationsRow{}
	for rows.Next() {
		var i ListUserConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.SchoolID,
			&i.TeacherID,
			&i.ParentID,
			&i.StudentID,
			&i.LastMessageAt,
			&i.CreatedAt,
			&i.TeacherName,
			&i.TeacherEmail,
			&i.ParentName,
			&i.ParentEmail,
			&i.StudentName,
			&i.LatestMessageContent,
			&i.LatestMessageAt,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsAsRead = `-- name: MarkAllNotificationsAsRead :exec
UPDATE notifications
SET is_read = TRUE
WHERE user_id = $1 AND is_read = FALSE
`

func (q *Queries) MarkAllNotificationsAsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsAsRead, userID)
	return err
}

const markMessagesAsRead = `-- name: MarkMessagesAsRead :exec
UPDATE messages
SET is_read = TRUE
WHERE conversation_id = $1 AND sender_id != $2 AND is_read = FALSE
`

type MarkMessagesAsReadParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	SenderID       uuid.UUID `json:"sender_id"`
}

func (q *Queries) MarkMessagesAsRead(ctx context.Context, arg MarkMessagesAsReadParams) error {
	_, err := q.db.Exec(ctx, markMessagesAsRead, arg.ConversationID, arg.SenderID)
	return err
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :exec
UPDATE notifications
SET is_read = TRUE
WHERE id = $1 AND user_id = $2
`

type MarkNotificationAsReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationAsRead, arg.ID, arg.UserID)
	return err
}

const touchConversation = `-- name: TouchConversation :exec
UPDATE conversations
SET last_message_at = NOW()
WHERE id = $1
`

func (q *Queries) TouchConversation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchConversation, id)
	return err
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :one
INSERT INTO user_device_tokens (user_id, fcm_token, platform, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (fcm_token)
DO UPDATE SET user_id = EXCLUDED.user_id, platform = EXCLUDED.platform, updated_at = NOW()
RETURNING id, user_id, fcm_token, platform, created_at, updated_at
`

type UpsertDeviceTokenParams struct {
	UserID   uuid.UUID `json:"user_id"`
	FcmToken string    `json:"fcm_token"`
	Platform string    `json:"platform"`
}

func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (UserDeviceToken, error) {
	row := q.db.QueryRow(ctx, upsertDeviceToken, arg.UserID, arg.FcmToken, arg.Platform)
	var i UserDeviceToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FcmToken,
		&i.Platform,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
