// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AnchorBatch struct {
	ID              uuid.UUID          `json:"id"`
	MerkleRoot      string             `json:"merkle_root"`
	BatchSize       int32              `json:"batch_size"`
	Network         string             `json:"network"`
	ContractAddress pgtype.Text        `json:"contract_address"`
	TxHash          pgtype.Text        `json:"tx_hash"`
	BlockNumber     pgtype.Int8        `json:"block_number"`
	AnchoredBy      pgtype.UUID        `json:"anchored_by"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	AnchoredAt      pgtype.Timestamptz `json:"anchored_at"`
}

type Announcement struct {
	ID        uuid.UUID          `json:"id"`
	ClassID   uuid.UUID          `json:"class_id"`
	TeacherID uuid.UUID          `json:"teacher_id"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
	Priority  string             `json:"priority"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Assignment struct {
	ID          uuid.UUID          `json:"id"`
	ClassID     uuid.UUID          `json:"class_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	MaxScore    int32              `json:"max_score"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AttendanceRecord struct {
	ID        uuid.UUID          `json:"id"`
	ClassID   uuid.UUID          `json:"class_id"`
	StudentID uuid.UUID          `json:"student_id"`
	Date      pgtype.Date        `json:"date"`
	Status    string             `json:"status"`
	Notes     string             `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Class struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	GradeLevel   string             `json:"grade_level"`
	TeacherID    uuid.UUID          `json:"teacher_id"`
	AcademicYear string             `json:"academic_year"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	SchoolID     uuid.UUID          `json:"school_id"`
}

type ClassEnrollment struct {
	ID         uuid.UUID          `json:"id"`
	ClassID    uuid.UUID          `json:"class_id"`
	StudentID  uuid.UUID          `json:"student_id"`
	EnrolledAt pgtype.Timestamptz `json:"enrolled_at"`
}

type Conversation struct {
	ID            uuid.UUID          `json:"id"`
	SchoolID      pgtype.UUID        `json:"school_id"`
	TeacherID     uuid.UUID          `json:"teacher_id"`
	ParentID      uuid.UUID          `json:"parent_id"`
	StudentID     pgtype.UUID        `json:"student_id"`
	LastMessageAt pgtype.Timestamptz `json:"last_message_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ExamMark struct {
	ID           uuid.UUID          `json:"id"`
	ClassID      uuid.UUID          `json:"class_id"`
	StudentID    uuid.UUID          `json:"student_id"`
	ExamName     string             `json:"exam_name"`
	AcademicYear string             `json:"academic_year"`
	Myanmar      pgtype.Numeric     `json:"myanmar"`
	English      pgtype.Numeric     `json:"english"`
	Maths        pgtype.Numeric     `json:"maths"`
	Phy          pgtype.Numeric     `json:"phy"`
	Chem         pgtype.Numeric     `json:"chem"`
	Bio          pgtype.Numeric     `json:"bio"`
	Geo          pgtype.Numeric     `json:"geo"`
	His          pgtype.Numeric     `json:"his"`
	Eco          pgtype.Numeric     `json:"eco"`
	Social       pgtype.Numeric     `json:"social"`
	Remarks      string             `json:"remarks"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type LessonPlan struct {
	ID                       uuid.UUID          `json:"id"`
	TeacherID                uuid.UUID          `json:"teacher_id"`
	Subject                  string             `json:"subject"`
	GradeLevel               string             `json:"grade_level"`
	Topic                    string             `json:"topic"`
	DurationMinutes          int32              `json:"duration_minutes"`
	GeneratedMarkdown        string             `json:"generated_markdown"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	GeneratedMarkdownBurmese string             `json:"generated_markdown_burmese"`
}

type Message struct {
	ID             uuid.UUID          `json:"id"`
	ConversationID uuid.UUID          `json:"conversation_id"`
	SenderID       uuid.UUID          `json:"sender_id"`
	Content        string             `json:"content"`
	IsRead         bool               `json:"is_read"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type MimuPcode struct {
	Pcode       string             `json:"pcode"`
	ParentPcode pgtype.Text        `json:"parent_pcode"`
	AdminLevel  int32              `json:"admin_level"`
	NameEn      string             `json:"name_en"`
	NameMy      string             `json:"name_my"`
	SrPcode     pgtype.Text        `json:"sr_pcode"`
	TsPcode     pgtype.Text        `json:"ts_pcode"`
	PcodeType   string             `json:"pcode_type"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Notification struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	Data      []byte             `json:"data"`
	IsRead    bool               `json:"is_read"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OfflineSyncBatch struct {
	ID              uuid.UUID          `json:"id"`
	BatchChecksum   string             `json:"batch_checksum"`
	SchoolID        uuid.UUID          `json:"school_id"`
	ClassID         uuid.UUID          `json:"class_id"`
	TeacherID       pgtype.UUID        `json:"teacher_id"`
	Period          string             `json:"period"`
	ProtocolVersion string             `json:"protocol_version"`
	TotalStudents   int32              `json:"total_students"`
	RawPayload      []byte             `json:"raw_payload"`
	SyncMethod      pgtype.Text        `json:"sync_method"`
	SyncedAt        pgtype.Timestamptz `json:"synced_at"`
}

type School struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Code            string             `json:"code"`
	Address         string             `json:"address"`
	City            string             `json:"city"`
	Region          string             `json:"region"`
	Phone           string             `json:"phone"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	PcodeSr         pgtype.Text        `json:"pcode_sr"`
	PcodeTs         pgtype.Text        `json:"pcode_ts"`
	PcodeWardVt     pgtype.Text        `json:"pcode_ward_vt"`
	PcodeLevel      pgtype.Text        `json:"pcode_level"`
	TownshipName    pgtype.Text        `json:"township_name"`
	WardVillageName pgtype.Text        `json:"ward_village_name"`
	SchoolCategory  pgtype.Text        `json:"school_category"`
	NameEn          pgtype.Text        `json:"name_en"`
	NameMy          pgtype.Text        `json:"name_my"`
}

type Submission struct {
	ID           uuid.UUID          `json:"id"`
	AssignmentID uuid.UUID          `json:"assignment_id"`
	StudentID    uuid.UUID          `json:"student_id"`
	Status       string             `json:"status"`
	Grade        pgtype.Numeric     `json:"grade"`
	Feedback     string             `json:"feedback"`
	SubmittedAt  pgtype.Timestamptz `json:"submitted_at"`
}

type User struct {
	ID                uuid.UUID          `json:"id"`
	Email             string             `json:"email"`
	PasswordHash      string             `json:"password_hash"`
	FullName          string             `json:"full_name"`
	Role              string             `json:"role"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	SchoolID          pgtype.UUID        `json:"school_id"`
	Did               pgtype.Text        `json:"did"`
	BlockchainAddress pgtype.Text        `json:"blockchain_address"`
	PublicKey         pgtype.Text        `json:"public_key"`
	CredentialHash    pgtype.Text        `json:"credential_hash"`
	MerkleRoot        pgtype.Text        `json:"merkle_root"`
	BlockchainTxHash  pgtype.Text        `json:"blockchain_tx_hash"`
	AnchorStatus      pgtype.Text        `json:"anchor_status"`
	ParentID          pgtype.UUID        `json:"parent_id"`
	AvatarURL         pgtype.Text        `json:"avatar_url"`
	Phone             pgtype.Text        `json:"phone"`
	Bio               pgtype.Text        `json:"bio"`
}

type UserDeviceToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	FcmToken  string             `json:"fcm_token"`
	Platform  string             `json:"platform"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type VerifiableCredential struct {
	ID                 uuid.UUID          `json:"id"`
	StudentID          uuid.UUID          `json:"student_id"`
	IssuerSchoolID     pgtype.UUID        `json:"issuer_school_id"`
	Did                string             `json:"did"`
	CredentialType     string             `json:"credential_type"`
	CredentialHash     string             `json:"credential_hash"`
	MerkleRoot         pgtype.Text        `json:"merkle_root"`
	MerkleProof        []byte             `json:"merkle_proof"`
	PolygonTxHash      pgtype.Text        `json:"polygon_tx_hash"`
	PolygonBlockNumber pgtype.Int8        `json:"polygon_block_number"`
	RawCredentialJson  []byte             `json:"raw_credential_json"`
	Signature          string             `json:"signature"`
	IsRevoked          bool               `json:"is_revoked"`
	RevocationReason   pgtype.Text        `json:"revocation_reason"`
	IssuedAt           pgtype.Timestamptz `json:"issued_at"`
}

type WholeChildProfile struct {
	ID                       uuid.UUID          `json:"id"`
	StudentID                uuid.UUID          `json:"student_id"`
	SchoolID                 uuid.UUID          `json:"school_id"`
	ClassID                  uuid.UUID          `json:"class_id"`
	AcademicYear             string             `json:"academic_year"`
	Period                   string             `json:"period"`
	AttendanceRatePct        pgtype.Numeric     `json:"attendance_rate_pct"`
	AcademicProfile          []byte             `json:"academic_profile"`
	PhysicalGrowthProfile    []byte             `json:"physical_growth_profile"`
	HealthVisibilityProfile  []byte             `json:"health_visibility_profile"`
	WellbeingProfile         []byte             `json:"wellbeing_profile"`
	SocialCitizenshipProfile []byte             `json:"social_citizenship_profile"`
	SyncSource               pgtype.Text        `json:"sync_source"`
	SyncRecordHash           pgtype.Text        `json:"sync_record_hash"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}
