// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Assignment struct {
	ID          uuid.UUID          `json:"id"`
	ClassID     uuid.UUID          `json:"class_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	MaxScore    int32              `json:"max_score"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AttendanceRecord struct {
	ID        uuid.UUID          `json:"id"`
	ClassID   uuid.UUID          `json:"class_id"`
	StudentID uuid.UUID          `json:"student_id"`
	Date      pgtype.Date        `json:"date"`
	Status    string             `json:"status"`
	Notes     string             `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Class struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	GradeLevel   string             `json:"grade_level"`
	TeacherID    uuid.UUID          `json:"teacher_id"`
	AcademicYear string             `json:"academic_year"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type ClassEnrollment struct {
	ID         uuid.UUID          `json:"id"`
	ClassID    uuid.UUID          `json:"class_id"`
	StudentID  uuid.UUID          `json:"student_id"`
	EnrolledAt pgtype.Timestamptz `json:"enrolled_at"`
}

type LessonPlan struct {
	ID                uuid.UUID          `json:"id"`
	TeacherID         uuid.UUID          `json:"teacher_id"`
	Subject           string             `json:"subject"`
	GradeLevel        string             `json:"grade_level"`
	Topic             string             `json:"topic"`
	DurationMinutes   int32              `json:"duration_minutes"`
	GeneratedMarkdown string             `json:"generated_markdown"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Submission struct {
	ID           uuid.UUID          `json:"id"`
	AssignmentID uuid.UUID          `json:"assignment_id"`
	StudentID    uuid.UUID          `json:"student_id"`
	Status       string             `json:"status"`
	Grade        pgtype.Numeric     `json:"grade"`
	Feedback     string             `json:"feedback"`
	SubmittedAt  pgtype.Timestamptz `json:"submitted_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FullName     string             `json:"full_name"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
