// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: pcodes.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPCodes = `-- name: CountPCodes :one
SELECT COUNT(*)::bigint AS total_pcodes
FROM mimu_pcodes
`

func (q *Queries) CountPCodes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPCodes)
	var total_pcodes int64
	err := row.Scan(&total_pcodes)
	return total_pcodes, err
}

const createPCode = `-- name: CreatePCode :one
INSERT INTO mimu_pcodes (
    pcode, parent_pcode, admin_level, name_en, name_my, sr_pcode, ts_pcode, pcode_type
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (pcode) DO UPDATE SET
    name_en = EXCLUDED.name_en,
    name_my = EXCLUDED.name_my
RETURNING pcode, parent_pcode, admin_level, name_en, name_my, sr_pcode, ts_pcode, pcode_type, created_at
`

type CreatePCodeParams struct {
	Pcode       string      `json:"pcode"`
	ParentPcode pgtype.Text `json:"parent_pcode"`
	AdminLevel  int32       `json:"admin_level"`
	NameEn      string      `json:"name_en"`
	NameMy      string      `json:"name_my"`
	SrPcode     pgtype.Text `json:"sr_pcode"`
	TsPcode     pgtype.Text `json:"ts_pcode"`
	PcodeType   string      `json:"pcode_type"`
}

func (q *Queries) CreatePCode(ctx context.Context, arg CreatePCodeParams) (MimuPcode, error) {
	row := q.db.QueryRow(ctx, createPCode,
		arg.Pcode,
		arg.ParentPcode,
		arg.AdminLevel,
		arg.NameEn,
		arg.NameMy,
		arg.SrPcode,
		arg.TsPcode,
		arg.PcodeType,
	)
	var i MimuPcode
	err := row.Scan(
		&i.Pcode,
		&i.ParentPcode,
		&i.AdminLevel,
		&i.NameEn,
		&i.NameMy,
		&i.SrPcode,
		&i.TsPcode,
		&i.PcodeType,
		&i.CreatedAt,
	)
	return i, err
}

const getPCode = `-- name: GetPCode :one
SELECT pcode, parent_pcode, admin_level, name_en, name_my, sr_pcode, ts_pcode, pcode_type, created_at
FROM mimu_pcodes
WHERE pcode = $1
`

func (q *Queries) GetPCode(ctx context.Context, pcode string) (MimuPcode, error) {
	row := q.db.QueryRow(ctx, getPCode, pcode)
	var i MimuPcode
	err := row.Scan(
		&i.Pcode,
		&i.ParentPcode,
		&i.AdminLevel,
		&i.NameEn,
		&i.NameMy,
		&i.SrPcode,
		&i.TsPcode,
		&i.PcodeType,
		&i.CreatedAt,
	)
	return i, err
}

const listStateRegions = `-- name: ListStateRegions :many
SELECT pcode, parent_pcode, admin_level, name_en, name_my, sr_pcode, ts_pcode, pcode_type, created_at
FROM mimu_pcodes
WHERE admin_level = 1
ORDER BY name_en ASC
`

func (q *Queries) ListStateRegions(ctx context.Context) ([]MimuPcode, error) {
	rows, err := q.db.Query(ctx, listStateRegions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MimuPcode{}
	for rows.Next() {
		var i MimuPcode
		if err := rows.Scan(
			&i.Pcode,
			&i.ParentPcode,
			&i.AdminLevel,
			&i.NameEn,
			&i.NameMy,
			&i.SrPcode,
			&i.TsPcode,
			&i.PcodeType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTownshipsBySR = `-- name: ListTownshipsBySR :many
SELECT pcode, parent_pcode, admin_level, name_en, name_my, sr_pcode, ts_pcode, pcode_type, created_at
FROM mimu_pcodes
WHERE admin_level = 3 AND sr_pcode = $1
ORDER BY name_en ASC
`

func (q *Queries) ListTownshipsBySR(ctx context.Context, srPcode pgtype.Text) ([]MimuPcode, error) {
	rows, err := q.db.Query(ctx, listTownshipsBySR, srPcode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MimuPcode{}
	for rows.Next() {
		var i MimuPcode
		if err := rows.Scan(
			&i.Pcode,
			&i.ParentPcode,
			&i.AdminLevel,
			&i.NameEn,
			&i.NameMy,
			&i.SrPcode,
			&i.TsPcode,
			&i.PcodeType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWardsByTownship = `-- name: ListWardsByTownship :many
SELECT pcode, parent_pcode, admin_level, name_en, name_my, sr_pcode, ts_pcode, pcode_type, created_at
FROM mimu_pcodes
WHERE admin_level = 4 AND ts_pcode = $1
ORDER BY name_en ASC
`

func (q *Queries) ListWardsByTownship(ctx context.Context, tsPcode pgtype.Text) ([]MimuPcode, error) {
	rows, err := q.db.Query(ctx, listWardsByTownship, tsPcode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MimuPcode{}
	for rows.Next() {
		var i MimuPcode
		if err := rows.Scan(
			&i.Pcode,
			&i.ParentPcode,
			&i.AdminLevel,
			&i.NameEn,
			&i.NameMy,
			&i.SrPcode,
			&i.TsPcode,
			&i.PcodeType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPCodes = `-- name: SearchPCodes :many
SELECT pcode, parent_pcode, admin_level, name_en, name_my, sr_pcode, ts_pcode, pcode_type, created_at
FROM mimu_pcodes
WHERE name_en ILIKE '%' || $1 || '%' OR name_my ILIKE '%' || $1 || '%' OR pcode ILIKE '%' || $1 || '%'
ORDER BY admin_level ASC, name_en ASC
LIMIT 50
`

func (q *Queries) SearchPCodes(ctx context.Context, dollar_1 pgtype.Text) ([]MimuPcode, error) {
	rows, err := q.db.Query(ctx, searchPCodes, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MimuPcode{}
	for rows.Next() {
		var i MimuPcode
		if err := rows.Scan(
			&i.Pcode,
			&i.ParentPcode,
			&i.AdminLevel,
			&i.NameEn,
			&i.NameMy,
			&i.SrPcode,
			&i.TsPcode,
			&i.PcodeType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
