// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountClassesBySchool(ctx context.Context, schoolID uuid.UUID) (int64, error)
	CountPCodes(ctx context.Context) (int64, error)
	CountSchools(ctx context.Context) (int64, error)
	CountSchoolsFiltered(ctx context.Context, arg CountSchoolsFilteredParams) (int64, error)
	CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error)
	CountUsersBySchoolAndRole(ctx context.Context, arg CountUsersBySchoolAndRoleParams) (int64, error)
	CreateAnchorBatch(ctx context.Context, arg CreateAnchorBatchParams) (AnchorBatch, error)
	CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error)
	CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (Assignment, error)
	CreateClass(ctx context.Context, arg CreateClassParams) (Class, error)
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) (ClassEnrollment, error)
	CreateLessonPlan(ctx context.Context, arg CreateLessonPlanParams) (LessonPlan, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateOfflineSyncBatch(ctx context.Context, arg CreateOfflineSyncBatchParams) (OfflineSyncBatch, error)
	CreatePCode(ctx context.Context, arg CreatePCodeParams) (MimuPcode, error)
	CreateSchool(ctx context.Context, arg CreateSchoolParams) (School, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CreateVerifiableCredential(ctx context.Context, arg CreateVerifiableCredentialParams) (VerifiableCredential, error)
	DeleteAssignment(ctx context.Context, id uuid.UUID) error
	DeleteClass(ctx context.Context, id uuid.UUID) error
	DeleteDeviceToken(ctx context.Context, fcmToken string) error
	DeleteEnrollment(ctx context.Context, arg DeleteEnrollmentParams) error
	DeleteExamMarksByClassAndExam(ctx context.Context, arg DeleteExamMarksByClassAndExamParams) error
	DeleteLessonPlan(ctx context.Context, id uuid.UUID) error
	DeleteSchool(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserDeviceToken(ctx context.Context, arg DeleteUserDeviceTokenParams) error
	GetAnchorBatchByRoot(ctx context.Context, merkleRoot string) (AnchorBatch, error)
	GetAssignmentByID(ctx context.Context, id uuid.UUID) (Assignment, error)
	GetClassAttendanceRoster(ctx context.Context, arg GetClassAttendanceRosterParams) ([]GetClassAttendanceRosterRow, error)
	GetClassByID(ctx context.Context, id uuid.UUID) (Class, error)
	GetClassExamRoster(ctx context.Context, arg GetClassExamRosterParams) ([]GetClassExamRosterRow, error)
	GetConversationByID(ctx context.Context, id uuid.UUID) (GetConversationByIDRow, error)
	GetLatestWholeChildProfileByStudent(ctx context.Context, studentID uuid.UUID) (GetLatestWholeChildProfileByStudentRow, error)
	GetLessonPlanByID(ctx context.Context, id uuid.UUID) (LessonPlan, error)
	GetOfflineSyncBatchByChecksum(ctx context.Context, batchChecksum string) (OfflineSyncBatch, error)
	GetPCode(ctx context.Context, pcode string) (MimuPcode, error)
	GetParentByStudentID(ctx context.Context, id uuid.UUID) (GetParentByStudentIDRow, error)
	GetSchoolByCode(ctx context.Context, code string) (School, error)
	GetSchoolByID(ctx context.Context, id uuid.UUID) (School, error)
	GetStudentAttendanceSummary(ctx context.Context, studentID uuid.UUID) ([]GetStudentAttendanceSummaryRow, error)
	GetSubmissionByAssignmentAndStudent(ctx context.Context, arg GetSubmissionByAssignmentAndStudentParams) (Submission, error)
	GetSubmissionByID(ctx context.Context, id uuid.UUID) (Submission, error)
	GetTeacherByStudentID(ctx context.Context, studentID uuid.UUID) (GetTeacherByStudentIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserProfileByID(ctx context.Context, id uuid.UUID) (GetUserProfileByIDRow, error)
	GetVerifiableCredentialByDID(ctx context.Context, did string) (VerifiableCredential, error)
	GetVerifiableCredentialByHash(ctx context.Context, credentialHash string) (VerifiableCredential, error)
	GetVerifiableCredentialByStudentID(ctx context.Context, studentID uuid.UUID) (VerifiableCredential, error)
	GetWholeChildProfileByStudentAndPeriod(ctx context.Context, arg GetWholeChildProfileByStudentAndPeriodParams) (GetWholeChildProfileByStudentAndPeriodRow, error)
	GradeSubmission(ctx context.Context, arg GradeSubmissionParams) (Submission, error)
	IsStudentEnrolled(ctx context.Context, arg IsStudentEnrolledParams) (bool, error)
	LinkStudentToParent(ctx context.Context, arg LinkStudentToParentParams) error
	ListAnchorBatches(ctx context.Context, limit int32) ([]AnchorBatch, error)
	ListAnnouncementsByClass(ctx context.Context, classID uuid.UUID) ([]ListAnnouncementsByClassRow, error)
	ListAnnouncementsForParent(ctx context.Context, parentID pgtype.UUID) ([]ListAnnouncementsForParentRow, error)
	ListAssignmentsByClassID(ctx context.Context, classID uuid.UUID) ([]Assignment, error)
	ListAttendanceByClassAndDate(ctx context.Context, arg ListAttendanceByClassAndDateParams) ([]ListAttendanceByClassAndDateRow, error)
	ListAttendanceByStudentID(ctx context.Context, studentID uuid.UUID) ([]ListAttendanceByStudentIDRow, error)
	ListClasses(ctx context.Context) ([]Class, error)
	ListClassesBySchool(ctx context.Context, schoolID uuid.UUID) ([]Class, error)
	ListClassesByStudentID(ctx context.Context, studentID uuid.UUID) ([]ListClassesByStudentIDRow, error)
	ListClassesByTeacher(ctx context.Context, teacherID uuid.UUID) ([]Class, error)
	ListDeviceTokensByUserID(ctx context.Context, userID uuid.UUID) ([]UserDeviceToken, error)
	ListDistinctExamsByClass(ctx context.Context, classID uuid.UUID) ([]ListDistinctExamsByClassRow, error)
	ListLessonPlansBySchoolAndGrade(ctx context.Context, arg ListLessonPlansBySchoolAndGradeParams) ([]LessonPlan, error)
	ListLessonPlansBySchoolID(ctx context.Context, schoolID pgtype.UUID) ([]LessonPlan, error)
	ListLessonPlansByTeacherID(ctx context.Context, teacherID uuid.UUID) ([]LessonPlan, error)
	ListMessagesByConversation(ctx context.Context, conversationID uuid.UUID) ([]ListMessagesByConversationRow, error)
	ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error)
	ListOfflineSyncBatchesBySchool(ctx context.Context, arg ListOfflineSyncBatchesBySchoolParams) ([]OfflineSyncBatch, error)
	ListParentsByClassID(ctx context.Context, classID uuid.UUID) ([]ListParentsByClassIDRow, error)
	ListPendingAssignmentsByStudentID(ctx context.Context, studentID uuid.UUID) ([]ListPendingAssignmentsByStudentIDRow, error)
	ListSchools(ctx context.Context) ([]School, error)
	ListSchoolsByPCodeSR(ctx context.Context, pcodeSr pgtype.Text) ([]School, error)
	ListSchoolsByPCodeTS(ctx context.Context, pcodeTs pgtype.Text) ([]School, error)
	ListSchoolsPaginated(ctx context.Context, arg ListSchoolsPaginatedParams) ([]School, error)
	ListStateRegions(ctx context.Context) ([]MimuPcode, error)
	ListStudentsByClassID(ctx context.Context, classID uuid.UUID) ([]ListStudentsByClassIDRow, error)
	ListStudentsByParentID(ctx context.Context, parentID pgtype.UUID) ([]ListStudentsByParentIDRow, error)
	ListStudentsBySchool(ctx context.Context, schoolID pgtype.UUID) ([]ListStudentsBySchoolRow, error)
	ListSubmissionsByAssignmentID(ctx context.Context, assignmentID uuid.UUID) ([]ListSubmissionsByAssignmentIDRow, error)
	ListSubmissionsByStudentID(ctx context.Context, studentID uuid.UUID) ([]ListSubmissionsByStudentIDRow, error)
	ListTownshipsBySR(ctx context.Context, srPcode pgtype.Text) ([]MimuPcode, error)
	ListUnanchoredCredentials(ctx context.Context) ([]VerifiableCredential, error)
	ListUserConversations(ctx context.Context, senderID uuid.UUID) ([]ListUserConversationsRow, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	ListUsersByRole(ctx context.Context, role string) ([]ListUsersByRoleRow, error)
	ListUsersBySchool(ctx context.Context, schoolID pgtype.UUID) ([]ListUsersBySchoolRow, error)
	ListUsersBySchoolAndRole(ctx context.Context, arg ListUsersBySchoolAndRoleParams) ([]ListUsersBySchoolAndRoleRow, error)
	ListWardsByTownship(ctx context.Context, tsPcode pgtype.Text) ([]MimuPcode, error)
	ListWholeChildProfilesByClassAndPeriod(ctx context.Context, arg ListWholeChildProfilesByClassAndPeriodParams) ([]ListWholeChildProfilesByClassAndPeriodRow, error)
	MarkAllNotificationsAsRead(ctx context.Context, userID uuid.UUID) error
	MarkMessagesAsRead(ctx context.Context, arg MarkMessagesAsReadParams) error
	MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) error
	RevokeCredential(ctx context.Context, arg RevokeCredentialParams) error
	SearchPCodes(ctx context.Context, dollar_1 pgtype.Text) ([]MimuPcode, error)
	TouchConversation(ctx context.Context, id uuid.UUID) error
	UpdateClass(ctx context.Context, arg UpdateClassParams) (Class, error)
	UpdateCredentialAnchor(ctx context.Context, arg UpdateCredentialAnchorParams) error
	UpdateLessonPlanBurmese(ctx context.Context, arg UpdateLessonPlanBurmeseParams) (LessonPlan, error)
	UpdateLessonPlanContent(ctx context.Context, arg UpdateLessonPlanContentParams) (LessonPlan, error)
	UpdateSchool(ctx context.Context, arg UpdateSchoolParams) (School, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
	UpdateUserAnchorStatus(ctx context.Context, arg UpdateUserAnchorStatusParams) error
	UpdateUserBlockchainIdentity(ctx context.Context, arg UpdateUserBlockchainIdentityParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error)
	UpsertAttendance(ctx context.Context, arg UpsertAttendanceParams) (AttendanceRecord, error)
	UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) (UserDeviceToken, error)
	UpsertExamMark(ctx context.Context, arg UpsertExamMarkParams) (ExamMark, error)
	UpsertSubmission(ctx context.Context, arg UpsertSubmissionParams) (Submission, error)
	UpsertWholeChildProfile(ctx context.Context, arg UpsertWholeChildProfileParams) (WholeChildProfile, error)
}

var _ Querier = (*Queries)(nil)
