// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: schools.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSchools = `-- name: CountSchools :one
SELECT COUNT(*)::bigint AS total_schools
FROM schools
`

func (q *Queries) CountSchools(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSchools)
	var total_schools int64
	err := row.Scan(&total_schools)
	return total_schools, err
}

const createSchool = `-- name: CreateSchool :one
INSERT INTO schools (
    name, code, address, city, region, phone, status,
    pcode_sr, pcode_ts, pcode_ward_vt, pcode_level, township_name, ward_village_name, school_category
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, name, code, address, city, region, phone, status, created_at, pcode_sr, pcode_ts, pcode_ward_vt, pcode_level, township_name, ward_village_name, school_category
`

type CreateSchoolParams struct {
	Name            string      `json:"name"`
	Code            string      `json:"code"`
	Address         string      `json:"address"`
	City            string      `json:"city"`
	Region          string      `json:"region"`
	Phone           string      `json:"phone"`
	Status          string      `json:"status"`
	PcodeSr         pgtype.Text `json:"pcode_sr"`
	PcodeTs         pgtype.Text `json:"pcode_ts"`
	PcodeWardVt     pgtype.Text `json:"pcode_ward_vt"`
	PcodeLevel      pgtype.Text `json:"pcode_level"`
	TownshipName    pgtype.Text `json:"township_name"`
	WardVillageName pgtype.Text `json:"ward_village_name"`
	SchoolCategory  pgtype.Text `json:"school_category"`
}

func (q *Queries) CreateSchool(ctx context.Context, arg CreateSchoolParams) (School, error) {
	row := q.db.QueryRow(ctx, createSchool,
		arg.Name,
		arg.Code,
		arg.Address,
		arg.City,
		arg.Region,
		arg.Phone,
		arg.Status,
		arg.PcodeSr,
		arg.PcodeTs,
		arg.PcodeWardVt,
		arg.PcodeLevel,
		arg.TownshipName,
		arg.WardVillageName,
		arg.SchoolCategory,
	)
	var i School
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Address,
		&i.City,
		&i.Region,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.PcodeSr,
		&i.PcodeTs,
		&i.PcodeWardVt,
		&i.PcodeLevel,
		&i.TownshipName,
		&i.WardVillageName,
		&i.SchoolCategory,
	)
	return i, err
}

const deleteSchool = `-- name: DeleteSchool :exec
DELETE FROM schools
WHERE id = $1
`

func (q *Queries) DeleteSchool(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSchool, id)
	return err
}

const getSchoolByCode = `-- name: GetSchoolByCode :one
SELECT id, name, code, address, city, region, phone, status, created_at, pcode_sr, pcode_ts, pcode_ward_vt, pcode_level, township_name, ward_village_name, school_category
FROM schools
WHERE code = $1
`

func (q *Queries) GetSchoolByCode(ctx context.Context, code string) (School, error) {
	row := q.db.QueryRow(ctx, getSchoolByCode, code)
	var i School
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Address,
		&i.City,
		&i.Region,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.PcodeSr,
		&i.PcodeTs,
		&i.PcodeWardVt,
		&i.PcodeLevel,
		&i.TownshipName,
		&i.WardVillageName,
		&i.SchoolCategory,
	)
	return i, err
}

const getSchoolByID = `-- name: GetSchoolByID :one
SELECT id, name, code, address, city, region, phone, status, created_at, pcode_sr, pcode_ts, pcode_ward_vt, pcode_level, township_name, ward_village_name, school_category
FROM schools
WHERE id = $1
`

func (q *Queries) GetSchoolByID(ctx context.Context, id uuid.UUID) (School, error) {
	row := q.db.QueryRow(ctx, getSchoolByID, id)
	var i School
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Address,
		&i.City,
		&i.Region,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.PcodeSr,
		&i.PcodeTs,
		&i.PcodeWardVt,
		&i.PcodeLevel,
		&i.TownshipName,
		&i.WardVillageName,
		&i.SchoolCategory,
	)
	return i, err
}

const listSchools = `-- name: ListSchools :many
SELECT id, name, code, address, city, region, phone, status, created_at, pcode_sr, pcode_ts, pcode_ward_vt, pcode_level, township_name, ward_village_name, school_category
FROM schools
ORDER BY name ASC
`

func (q *Queries) ListSchools(ctx context.Context) ([]School, error) {
	rows, err := q.db.Query(ctx, listSchools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []School{}
	for rows.Next() {
		var i School
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Address,
			&i.City,
			&i.Region,
			&i.Phone,
			&i.Status,
			&i.CreatedAt,
			&i.PcodeSr,
			&i.PcodeTs,
			&i.PcodeWardVt,
			&i.PcodeLevel,
			&i.TownshipName,
			&i.WardVillageName,
			&i.SchoolCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchoolsByPCodeSR = `-- name: ListSchoolsByPCodeSR :many
SELECT id, name, code, address, city, region, phone, status, created_at, pcode_sr, pcode_ts, pcode_ward_vt, pcode_level, township_name, ward_village_name, school_category
FROM schools
WHERE pcode_sr = $1
ORDER BY name ASC
`

func (q *Queries) ListSchoolsByPCodeSR(ctx context.Context, pcodeSr pgtype.Text) ([]School, error) {
	rows, err := q.db.Query(ctx, listSchoolsByPCodeSR, pcodeSr)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []School{}
	for rows.Next() {
		var i School
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Address,
			&i.City,
			&i.Region,
			&i.Phone,
			&i.Status,
			&i.CreatedAt,
			&i.PcodeSr,
			&i.PcodeTs,
			&i.PcodeWardVt,
			&i.PcodeLevel,
			&i.TownshipName,
			&i.WardVillageName,
			&i.SchoolCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchoolsByPCodeTS = `-- name: ListSchoolsByPCodeTS :many
SELECT id, name, code, address, city, region, phone, status, created_at, pcode_sr, pcode_ts, pcode_ward_vt, pcode_level, township_name, ward_village_name, school_category
FROM schools
WHERE pcode_ts = $1
ORDER BY name ASC
`

func (q *Queries) ListSchoolsByPCodeTS(ctx context.Context, pcodeTs pgtype.Text) ([]School, error) {
	rows, err := q.db.Query(ctx, listSchoolsByPCodeTS, pcodeTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []School{}
	for rows.Next() {
		var i School
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Address,
			&i.City,
			&i.Region,
			&i.Phone,
			&i.Status,
			&i.CreatedAt,
			&i.PcodeSr,
			&i.PcodeTs,
			&i.PcodeWardVt,
			&i.PcodeLevel,
			&i.TownshipName,
			&i.WardVillageName,
			&i.SchoolCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchool = `-- name: UpdateSchool :one
UPDATE schools
SET name = COALESCE($2, name),
    address = COALESCE($3, address),
    city = COALESCE($4, city),
    region = COALESCE($5, region),
    phone = COALESCE($6, phone),
    status = COALESCE($7, status),
    pcode_sr = COALESCE($8, pcode_sr),
    pcode_ts = COALESCE($9, pcode_ts),
    pcode_ward_vt = COALESCE($10, pcode_ward_vt),
    pcode_level = COALESCE($11, pcode_level),
    township_name = COALESCE($12, township_name),
    ward_village_name = COALESCE($13, ward_village_name),
    school_category = COALESCE($14, school_category)
WHERE id = $1
RETURNING id, name, code, address, city, region, phone, status, created_at, pcode_sr, pcode_ts, pcode_ward_vt, pcode_level, township_name, ward_village_name, school_category
`

type UpdateSchoolParams struct {
	ID              uuid.UUID   `json:"id"`
	Name            string      `json:"name"`
	Address         string      `json:"address"`
	City            string      `json:"city"`
	Region          string      `json:"region"`
	Phone           string      `json:"phone"`
	Status          string      `json:"status"`
	PcodeSr         pgtype.Text `json:"pcode_sr"`
	PcodeTs         pgtype.Text `json:"pcode_ts"`
	PcodeWardVt     pgtype.Text `json:"pcode_ward_vt"`
	PcodeLevel      pgtype.Text `json:"pcode_level"`
	TownshipName    pgtype.Text `json:"township_name"`
	WardVillageName pgtype.Text `json:"ward_village_name"`
	SchoolCategory  pgtype.Text `json:"school_category"`
}

func (q *Queries) UpdateSchool(ctx context.Context, arg UpdateSchoolParams) (School, error) {
	row := q.db.QueryRow(ctx, updateSchool,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.City,
		arg.Region,
		arg.Phone,
		arg.Status,
		arg.PcodeSr,
		arg.PcodeTs,
		arg.PcodeWardVt,
		arg.PcodeLevel,
		arg.TownshipName,
		arg.WardVillageName,
		arg.SchoolCategory,
	)
	var i School
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Address,
		&i.City,
		&i.Region,
		&i.Phone,
		&i.Status,
		&i.CreatedAt,
		&i.PcodeSr,
		&i.PcodeTs,
		&i.PcodeWardVt,
		&i.PcodeLevel,
		&i.TownshipName,
		&i.WardVillageName,
		&i.SchoolCategory,
	)
	return i, err
}
