// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: submissions.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSubmissionByAssignmentAndStudent = `-- name: GetSubmissionByAssignmentAndStudent :one
SELECT id, assignment_id, student_id, status, grade, feedback, submitted_at
FROM submissions
WHERE assignment_id = $1 AND student_id = $2
`

type GetSubmissionByAssignmentAndStudentParams struct {
	AssignmentID uuid.UUID `json:"assignment_id"`
	StudentID    uuid.UUID `json:"student_id"`
}

func (q *Queries) GetSubmissionByAssignmentAndStudent(ctx context.Context, arg GetSubmissionByAssignmentAndStudentParams) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmissionByAssignmentAndStudent, arg.AssignmentID, arg.StudentID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.StudentID,
		&i.Status,
		&i.Grade,
		&i.Feedback,
		&i.SubmittedAt,
	)
	return i, err
}

const getSubmissionByID = `-- name: GetSubmissionByID :one
SELECT id, assignment_id, student_id, status, grade, feedback, submitted_at
FROM submissions
WHERE id = $1
`

func (q *Queries) GetSubmissionByID(ctx context.Context, id uuid.UUID) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmissionByID, id)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.StudentID,
		&i.Status,
		&i.Grade,
		&i.Feedback,
		&i.SubmittedAt,
	)
	return i, err
}

const gradeSubmission = `-- name: GradeSubmission :one
UPDATE submissions
SET grade = $2,
    feedback = $3,
    status = 'graded'
WHERE id = $1
RETURNING id, assignment_id, student_id, status, grade, feedback, submitted_at
`

type GradeSubmissionParams struct {
	ID       uuid.UUID      `json:"id"`
	Grade    pgtype.Numeric `json:"grade"`
	Feedback string         `json:"feedback"`
}

func (q *Queries) GradeSubmission(ctx context.Context, arg GradeSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, gradeSubmission, arg.ID, arg.Grade, arg.Feedback)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.StudentID,
		&i.Status,
		&i.Grade,
		&i.Feedback,
		&i.SubmittedAt,
	)
	return i, err
}

const listSubmissionsByAssignmentID = `-- name: ListSubmissionsByAssignmentID :many
SELECT s.id, s.assignment_id, s.student_id, u.full_name AS student_name, u.email AS student_email, s.status, s.grade, s.feedback, s.submitted_at
FROM submissions s
JOIN users u ON s.student_id = u.id
WHERE s.assignment_id = $1
ORDER BY s.submitted_at DESC
`

type ListSubmissionsByAssignmentIDRow struct {
	ID           uuid.UUID          `json:"id"`
	AssignmentID uuid.UUID          `json:"assignment_id"`
	StudentID    uuid.UUID          `json:"student_id"`
	StudentName  string             `json:"student_name"`
	StudentEmail string             `json:"student_email"`
	Status       string             `json:"status"`
	Grade        pgtype.Numeric     `json:"grade"`
	Feedback     string             `json:"feedback"`
	SubmittedAt  pgtype.Timestamptz `json:"submitted_at"`
}

func (q *Queries) ListSubmissionsByAssignmentID(ctx context.Context, assignmentID uuid.UUID) ([]ListSubmissionsByAssignmentIDRow, error) {
	rows, err := q.db.Query(ctx, listSubmissionsByAssignmentID, assignmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubmissionsByAssignmentIDRow{}
	for rows.Next() {
		var i ListSubmissionsByAssignmentIDRow
		if err := rows.Scan(
			&i.ID,
			&i.AssignmentID,
			&i.StudentID,
			&i.StudentName,
			&i.StudentEmail,
			&i.Status,
			&i.Grade,
			&i.Feedback,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionsByStudentID = `-- name: ListSubmissionsByStudentID :many
SELECT s.id, s.assignment_id, a.title AS assignment_title, s.student_id, s.status, s.grade, s.feedback, s.submitted_at
FROM submissions s
JOIN assignments a ON s.assignment_id = a.id
WHERE s.student_id = $1
ORDER BY s.submitted_at DESC
`

type ListSubmissionsByStudentIDRow struct {
	ID              uuid.UUID          `json:"id"`
	AssignmentID    uuid.UUID          `json:"assignment_id"`
	AssignmentTitle string             `json:"assignment_title"`
	StudentID       uuid.UUID          `json:"student_id"`
	Status          string             `json:"status"`
	Grade           pgtype.Numeric     `json:"grade"`
	Feedback        string             `json:"feedback"`
	SubmittedAt     pgtype.Timestamptz `json:"submitted_at"`
}

func (q *Queries) ListSubmissionsByStudentID(ctx context.Context, studentID uuid.UUID) ([]ListSubmissionsByStudentIDRow, error) {
	rows, err := q.db.Query(ctx, listSubmissionsByStudentID, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubmissionsByStudentIDRow{}
	for rows.Next() {
		var i ListSubmissionsByStudentIDRow
		if err := rows.Scan(
			&i.ID,
			&i.AssignmentID,
			&i.AssignmentTitle,
			&i.StudentID,
			&i.Status,
			&i.Grade,
			&i.Feedback,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSubmission = `-- name: UpsertSubmission :one
INSERT INTO submissions (assignment_id, student_id, status, submitted_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (assignment_id, student_id)
DO UPDATE SET
    status = EXCLUDED.status,
    submitted_at = NOW()
RETURNING id, assignment_id, student_id, status, grade, feedback, submitted_at
`

type UpsertSubmissionParams struct {
	AssignmentID uuid.UUID `json:"assignment_id"`
	StudentID    uuid.UUID `json:"student_id"`
	Status       string    `json:"status"`
}

func (q *Queries) UpsertSubmission(ctx context.Context, arg UpsertSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, upsertSubmission, arg.AssignmentID, arg.StudentID, arg.Status)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.StudentID,
		&i.Status,
		&i.Grade,
		&i.Feedback,
		&i.SubmittedAt,
	)
	return i, err
}
