// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsersBySchoolAndRole = `-- name: CountUsersBySchoolAndRole :one
SELECT COUNT(*)::bigint AS total
FROM users
WHERE school_id = $1 AND role = $2
`

type CountUsersBySchoolAndRoleParams struct {
	SchoolID pgtype.UUID `json:"school_id"`
	Role     string      `json:"role"`
}

func (q *Queries) CountUsersBySchoolAndRole(ctx context.Context, arg CountUsersBySchoolAndRoleParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersBySchoolAndRole, arg.SchoolID, arg.Role)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, full_name, role, school_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, password_hash, full_name, role, school_id, created_at
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	FullName     string      `json:"full_name"`
	Role         string      `json:"role"`
	SchoolID     pgtype.UUID `json:"school_id"`
}

type CreateUserRow struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FullName     string             `json:"full_name"`
	Role         string             `json:"role"`
	SchoolID     pgtype.UUID        `json:"school_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.Role,
		arg.SchoolID,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.SchoolID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, full_name, role, school_id, created_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FullName     string             `json:"full_name"`
	Role         string             `json:"role"`
	SchoolID     pgtype.UUID        `json:"school_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.SchoolID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, full_name, role, school_id, created_at,
       did, blockchain_address, public_key, credential_hash, merkle_root, blockchain_tx_hash, anchor_status,
       parent_id
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID                uuid.UUID          `json:"id"`
	Email             string             `json:"email"`
	PasswordHash      string             `json:"password_hash"`
	FullName          string             `json:"full_name"`
	Role              string             `json:"role"`
	SchoolID          pgtype.UUID        `json:"school_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	Did               pgtype.Text        `json:"did"`
	BlockchainAddress pgtype.Text        `json:"blockchain_address"`
	PublicKey         pgtype.Text        `json:"public_key"`
	CredentialHash    pgtype.Text        `json:"credential_hash"`
	MerkleRoot        pgtype.Text        `json:"merkle_root"`
	BlockchainTxHash  pgtype.Text        `json:"blockchain_tx_hash"`
	AnchorStatus      pgtype.Text        `json:"anchor_status"`
	ParentID          pgtype.UUID        `json:"parent_id"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.SchoolID,
		&i.CreatedAt,
		&i.Did,
		&i.BlockchainAddress,
		&i.PublicKey,
		&i.CredentialHash,
		&i.MerkleRoot,
		&i.BlockchainTxHash,
		&i.AnchorStatus,
		&i.ParentID,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, email, password_hash, full_name, role, school_id, created_at
FROM users
WHERE phone IS NOT NULL
  AND phone != ''
  AND (phone = $1 OR regexp_replace(phone, '[^0-9]', '', 'g') = $2)
LIMIT 1
`

type GetUserByPhoneParams struct {
	Phone   pgtype.Text `json:"phone"`
	Phone_2 pgtype.Text `json:"phone_2"`
}

type GetUserByPhoneRow struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FullName     string             `json:"full_name"`
	Role         string             `json:"role"`
	SchoolID     pgtype.UUID        `json:"school_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByPhone(ctx context.Context, arg GetUserByPhoneParams) (GetUserByPhoneRow, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, arg.Phone, arg.Phone_2)
	var i GetUserByPhoneRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.SchoolID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserProfileByID = `-- name: GetUserProfileByID :one
SELECT u.id, u.email, u.password_hash, u.full_name, u.role, u.school_id, u.created_at,
       u.did, u.blockchain_address, u.public_key, u.credential_hash, u.merkle_root, u.blockchain_tx_hash, u.anchor_status,
       u.parent_id, u.avatar_url, u.phone, u.bio,
       COALESCE(s.name_my, s.name, '') as school_name,
       COALESCE(s.name_en, '') as school_name_en,
       COALESCE(s.code, '') as school_code,
       COALESCE(s.region, '') as school_region,
       COALESCE(s.township_name, '') as school_township
FROM users u
LEFT JOIN schools s ON s.id = u.school_id
WHERE u.id = $1
`

type GetUserProfileByIDRow struct {
	ID                uuid.UUID          `json:"id"`
	Email             string             `json:"email"`
	PasswordHash      string             `json:"password_hash"`
	FullName          string             `json:"full_name"`
	Role              string             `json:"role"`
	SchoolID          pgtype.UUID        `json:"school_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	Did               pgtype.Text        `json:"did"`
	BlockchainAddress pgtype.Text        `json:"blockchain_address"`
	PublicKey         pgtype.Text        `json:"public_key"`
	CredentialHash    pgtype.Text        `json:"credential_hash"`
	MerkleRoot        pgtype.Text        `json:"merkle_root"`
	BlockchainTxHash  pgtype.Text        `json:"blockchain_tx_hash"`
	AnchorStatus      pgtype.Text        `json:"anchor_status"`
	ParentID          pgtype.UUID        `json:"parent_id"`
	AvatarUrl         pgtype.Text        `json:"avatar_url"`
	Phone             pgtype.Text        `json:"phone"`
	Bio               pgtype.Text        `json:"bio"`
	SchoolName        string             `json:"school_name"`
	SchoolNameEn      string             `json:"school_name_en"`
	SchoolCode        string             `json:"school_code"`
	SchoolRegion      string             `json:"school_region"`
	SchoolTownship    string             `json:"school_township"`
}

func (q *Queries) GetUserProfileByID(ctx context.Context, id uuid.UUID) (GetUserProfileByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserProfileByID, id)
	var i GetUserProfileByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.SchoolID,
		&i.CreatedAt,
		&i.Did,
		&i.BlockchainAddress,
		&i.PublicKey,
		&i.CredentialHash,
		&i.MerkleRoot,
		&i.BlockchainTxHash,
		&i.AnchorStatus,
		&i.ParentID,
		&i.AvatarUrl,
		&i.Phone,
		&i.Bio,
		&i.SchoolName,
		&i.SchoolNameEn,
		&i.SchoolCode,
		&i.SchoolRegion,
		&i.SchoolTownship,
	)
	return i, err
}

const linkStudentToParent = `-- name: LinkStudentToParent :exec
UPDATE users
SET parent_id = $2
WHERE id = $1
`

type LinkStudentToParentParams struct {
	ID       uuid.UUID   `json:"id"`
	ParentID pgtype.UUID `json:"parent_id"`
}

func (q *Queries) LinkStudentToParent(ctx context.Context, arg LinkStudentToParentParams) error {
	_, err := q.db.Exec(ctx, linkStudentToParent, arg.ID, arg.ParentID)
	return err
}

const listStudentsByParentID = `-- name: ListStudentsByParentID :many
WITH latest_enrollments AS (
    SELECT DISTINCT ON (student_id) student_id, class_id, enrolled_at
    FROM class_enrollments
    ORDER BY student_id, enrolled_at DESC
)
SELECT u.id, u.email, u.full_name, u.role, u.school_id, u.created_at,
       u.did, u.blockchain_address, u.public_key, u.credential_hash, u.merkle_root, u.blockchain_tx_hash, u.anchor_status,
       c.id as class_id, c.name as class_name, c.grade_level,
       COALESCE(NULLIF(s.name_my, ''), s.name) as school_name,
       s.name_en as school_name_en, s.name_my as school_name_my,
       s.code as school_code, s.region as school_region, s.township_name as school_township
FROM users u
LEFT JOIN latest_enrollments le ON le.student_id = u.id
LEFT JOIN classes c ON c.id = le.class_id
LEFT JOIN schools s ON s.id = u.school_id
WHERE u.parent_id = $1 AND u.role = 'student'
ORDER BY 
    CASE WHEN c.grade_level = 'KG' THEN 0 ELSE 1 END,
    c.grade_level ASC,
    u.full_name ASC
`

type ListStudentsByParentIDRow struct {
	ID                uuid.UUID          `json:"id"`
	Email             string             `json:"email"`
	FullName          string             `json:"full_name"`
	Role              string             `json:"role"`
	SchoolID          pgtype.UUID        `json:"school_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	Did               pgtype.Text        `json:"did"`
	BlockchainAddress pgtype.Text        `json:"blockchain_address"`
	PublicKey         pgtype.Text        `json:"public_key"`
	CredentialHash    pgtype.Text        `json:"credential_hash"`
	MerkleRoot        pgtype.Text        `json:"merkle_root"`
	BlockchainTxHash  pgtype.Text        `json:"blockchain_tx_hash"`
	AnchorStatus      pgtype.Text        `json:"anchor_status"`
	ClassID           pgtype.UUID        `json:"class_id"`
	ClassName         pgtype.Text        `json:"class_name"`
	GradeLevel        pgtype.Text        `json:"grade_level"`
	SchoolName        string             `json:"school_name"`
	SchoolNameEn      pgtype.Text        `json:"school_name_en"`
	SchoolNameMy      pgtype.Text        `json:"school_name_my"`
	SchoolCode        pgtype.Text        `json:"school_code"`
	SchoolRegion      pgtype.Text        `json:"school_region"`
	SchoolTownship    pgtype.Text        `json:"school_township"`
}

func (q *Queries) ListStudentsByParentID(ctx context.Context, parentID pgtype.UUID) ([]ListStudentsByParentIDRow, error) {
	rows, err := q.db.Query(ctx, listStudentsByParentID, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentsByParentIDRow{}
	for rows.Next() {
		var i ListStudentsByParentIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.Role,
			&i.SchoolID,
			&i.CreatedAt,
			&i.Did,
			&i.BlockchainAddress,
			&i.PublicKey,
			&i.CredentialHash,
			&i.MerkleRoot,
			&i.BlockchainTxHash,
			&i.AnchorStatus,
			&i.ClassID,
			&i.ClassName,
			&i.GradeLevel,
			&i.SchoolName,
			&i.SchoolNameEn,
			&i.SchoolNameMy,
			&i.SchoolCode,
			&i.SchoolRegion,
			&i.SchoolTownship,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentsBySchool = `-- name: ListStudentsBySchool :many
WITH latest_enrollments AS (
    SELECT DISTINCT ON (student_id) student_id, class_id, enrolled_at
    FROM class_enrollments
    ORDER BY student_id, enrolled_at DESC
)
SELECT u.id, u.email, u.full_name, u.role, u.school_id, u.created_at,
       c.id as class_id, c.name as class_name, c.grade_level,
       COALESCE(NULLIF(s.name_my, ''), s.name) as school_name
FROM users u
LEFT JOIN latest_enrollments le ON le.student_id = u.id
LEFT JOIN classes c ON c.id = le.class_id
LEFT JOIN schools s ON s.id = u.school_id
WHERE u.school_id = $1 AND u.role = 'student'
ORDER BY 
    CASE 
        WHEN c.grade_level = 'KG' THEN 0
        WHEN c.grade_level = 'Grade 1' THEN 1
        WHEN c.grade_level = 'Grade 2' THEN 2
        WHEN c.grade_level = 'Grade 3' THEN 3
        WHEN c.grade_level = 'Grade 4' THEN 4
        WHEN c.grade_level = 'Grade 5' THEN 5
        WHEN c.grade_level = 'Grade 6' THEN 6
        WHEN c.grade_level = 'Grade 7' THEN 7
        WHEN c.grade_level = 'Grade 8' THEN 8
        WHEN c.grade_level = 'Grade 9' THEN 9
        WHEN c.grade_level = 'Grade 10' THEN 10
        WHEN c.grade_level = 'Grade 11' THEN 11
        WHEN c.grade_level = 'Grade 12' THEN 12
        ELSE 13
    END,
    c.name ASC,
    u.full_name ASC
`

type ListStudentsBySchoolRow struct {
	ID         uuid.UUID          `json:"id"`
	Email      string             `json:"email"`
	FullName   string             `json:"full_name"`
	Role       string             `json:"role"`
	SchoolID   pgtype.UUID        `json:"school_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ClassID    pgtype.UUID        `json:"class_id"`
	ClassName  pgtype.Text        `json:"class_name"`
	GradeLevel pgtype.Text        `json:"grade_level"`
	SchoolName string             `json:"school_name"`
}

func (q *Queries) ListStudentsBySchool(ctx context.Context, schoolID pgtype.UUID) ([]ListStudentsBySchoolRow, error) {
	rows, err := q.db.Query(ctx, listStudentsBySchool, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentsBySchoolRow{}
	for rows.Next() {
		var i ListStudentsBySchoolRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.Role,
			&i.SchoolID,
			&i.CreatedAt,
			&i.ClassID,
			&i.ClassName,
			&i.GradeLevel,
			&i.SchoolName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, full_name, role, school_id, created_at
FROM users
ORDER BY created_at DESC
`

type ListUsersRow struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	FullName  string             `json:"full_name"`
	Role      string             `json:"role"`
	SchoolID  pgtype.UUID        `json:"school_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.Role,
			&i.SchoolID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByRole = `-- name: ListUsersByRole :many
SELECT id, email, full_name, role, school_id, created_at
FROM users
WHERE role = $1
ORDER BY full_name ASC
`

type ListUsersByRoleRow struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	FullName  string             `json:"full_name"`
	Role      string             `json:"role"`
	SchoolID  pgtype.UUID        `json:"school_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUsersByRole(ctx context.Context, role string) ([]ListUsersByRoleRow, error) {
	rows, err := q.db.Query(ctx, listUsersByRole, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersByRoleRow{}
	for rows.Next() {
		var i ListUsersByRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.Role,
			&i.SchoolID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersBySchool = `-- name: ListUsersBySchool :many
SELECT id, email, full_name, role, school_id, created_at
FROM users
WHERE school_id = $1
ORDER BY full_name ASC
`

type ListUsersBySchoolRow struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	FullName  string             `json:"full_name"`
	Role      string             `json:"role"`
	SchoolID  pgtype.UUID        `json:"school_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUsersBySchool(ctx context.Context, schoolID pgtype.UUID) ([]ListUsersBySchoolRow, error) {
	rows, err := q.db.Query(ctx, listUsersBySchool, schoolID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersBySchoolRow{}
	for rows.Next() {
		var i ListUsersBySchoolRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.Role,
			&i.SchoolID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersBySchoolAndRole = `-- name: ListUsersBySchoolAndRole :many
SELECT id, email, full_name, role, school_id, created_at
FROM users
WHERE school_id = $1 AND role = $2
ORDER BY full_name ASC
`

type ListUsersBySchoolAndRoleParams struct {
	SchoolID pgtype.UUID `json:"school_id"`
	Role     string      `json:"role"`
}

type ListUsersBySchoolAndRoleRow struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	FullName  string             `json:"full_name"`
	Role      string             `json:"role"`
	SchoolID  pgtype.UUID        `json:"school_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUsersBySchoolAndRole(ctx context.Context, arg ListUsersBySchoolAndRoleParams) ([]ListUsersBySchoolAndRoleRow, error) {
	rows, err := q.db.Query(ctx, listUsersBySchoolAndRole, arg.SchoolID, arg.Role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersBySchoolAndRoleRow{}
	for rows.Next() {
		var i ListUsersBySchoolAndRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.Role,
			&i.SchoolID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET full_name = COALESCE($2, full_name),
    email = COALESCE($3, email),
    school_id = COALESCE($4, school_id)
WHERE id = $1
RETURNING id, email, password_hash, full_name, role, school_id, created_at
`

type UpdateUserParams struct {
	ID       uuid.UUID   `json:"id"`
	FullName string      `json:"full_name"`
	Email    string      `json:"email"`
	SchoolID pgtype.UUID `json:"school_id"`
}

type UpdateUserRow struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FullName     string             `json:"full_name"`
	Role         string             `json:"role"`
	SchoolID     pgtype.UUID        `json:"school_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.SchoolID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.SchoolID,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET full_name = COALESCE($2, full_name),
    email = COALESCE($3, email),
    avatar_url = CASE WHEN $4::boolean THEN $5::text ELSE avatar_url END,
    phone = CASE WHEN $6::boolean THEN $7::text ELSE phone END,
    bio = CASE WHEN $8::boolean THEN $9::text ELSE bio END
WHERE id = $1
RETURNING id, email, password_hash, full_name, role, school_id, created_at, avatar_url, phone, bio
`

type UpdateUserProfileParams struct {
	ID       uuid.UUID `json:"id"`
	FullName string    `json:"full_name"`
	Email    string    `json:"email"`
	Column4  bool      `json:"column_4"`
	Column5  string    `json:"column_5"`
	Column6  bool      `json:"column_6"`
	Column7  string    `json:"column_7"`
	Column8  bool      `json:"column_8"`
	Column9  string    `json:"column_9"`
}

type UpdateUserProfileRow struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FullName     string             `json:"full_name"`
	Role         string             `json:"role"`
	SchoolID     pgtype.UUID        `json:"school_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	Phone        pgtype.Text        `json:"phone"`
	Bio          pgtype.Text        `json:"bio"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Column9,
	)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.SchoolID,
		&i.CreatedAt,
		&i.AvatarUrl,
		&i.Phone,
		&i.Bio,
	)
	return i, err
}
