// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: whole_child.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOfflineSyncBatch = `-- name: CreateOfflineSyncBatch :one
INSERT INTO offline_sync_batches (
    batch_checksum,
    school_id,
    class_id,
    teacher_id,
    period,
    protocol_version,
    total_students,
    raw_payload,
    sync_method
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, batch_checksum, school_id, class_id, teacher_id, period, protocol_version, total_students, raw_payload, sync_method, synced_at
`

type CreateOfflineSyncBatchParams struct {
	BatchChecksum   string      `json:"batch_checksum"`
	SchoolID        uuid.UUID   `json:"school_id"`
	ClassID         uuid.UUID   `json:"class_id"`
	TeacherID       pgtype.UUID `json:"teacher_id"`
	Period          string      `json:"period"`
	ProtocolVersion string      `json:"protocol_version"`
	TotalStudents   int32       `json:"total_students"`
	RawPayload      []byte      `json:"raw_payload"`
	SyncMethod      pgtype.Text `json:"sync_method"`
}

func (q *Queries) CreateOfflineSyncBatch(ctx context.Context, arg CreateOfflineSyncBatchParams) (OfflineSyncBatch, error) {
	row := q.db.QueryRow(ctx, createOfflineSyncBatch,
		arg.BatchChecksum,
		arg.SchoolID,
		arg.ClassID,
		arg.TeacherID,
		arg.Period,
		arg.ProtocolVersion,
		arg.TotalStudents,
		arg.RawPayload,
		arg.SyncMethod,
	)
	var i OfflineSyncBatch
	err := row.Scan(
		&i.ID,
		&i.BatchChecksum,
		&i.SchoolID,
		&i.ClassID,
		&i.TeacherID,
		&i.Period,
		&i.ProtocolVersion,
		&i.TotalStudents,
		&i.RawPayload,
		&i.SyncMethod,
		&i.SyncedAt,
	)
	return i, err
}

const getLatestWholeChildProfileByStudent = `-- name: GetLatestWholeChildProfileByStudent :one
SELECT 
    wcp.id, wcp.student_id, wcp.school_id, wcp.class_id, wcp.academic_year, wcp.period, wcp.attendance_rate_pct, wcp.academic_profile, wcp.physical_growth_profile, wcp.health_visibility_profile, wcp.wellbeing_profile, wcp.social_citizenship_profile, wcp.sync_source, wcp.sync_record_hash, wcp.created_at, wcp.updated_at,
    u.full_name AS student_name,
    u.email AS student_email,
    u.did AS student_did
FROM whole_child_profiles wcp
JOIN users u ON u.id = wcp.student_id
WHERE wcp.student_id = $1
ORDER BY wcp.period DESC, wcp.updated_at DESC
LIMIT 1
`

type GetLatestWholeChildProfileByStudentRow struct {
	ID                       uuid.UUID          `json:"id"`
	StudentID                uuid.UUID          `json:"student_id"`
	SchoolID                 uuid.UUID          `json:"school_id"`
	ClassID                  uuid.UUID          `json:"class_id"`
	AcademicYear             string             `json:"academic_year"`
	Period                   string             `json:"period"`
	AttendanceRatePct        pgtype.Numeric     `json:"attendance_rate_pct"`
	AcademicProfile          []byte             `json:"academic_profile"`
	PhysicalGrowthProfile    []byte             `json:"physical_growth_profile"`
	HealthVisibilityProfile  []byte             `json:"health_visibility_profile"`
	WellbeingProfile         []byte             `json:"wellbeing_profile"`
	SocialCitizenshipProfile []byte             `json:"social_citizenship_profile"`
	SyncSource               pgtype.Text        `json:"sync_source"`
	SyncRecordHash           pgtype.Text        `json:"sync_record_hash"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	StudentName              string             `json:"student_name"`
	StudentEmail             string             `json:"student_email"`
	StudentDid               pgtype.Text        `json:"student_did"`
}

func (q *Queries) GetLatestWholeChildProfileByStudent(ctx context.Context, studentID uuid.UUID) (GetLatestWholeChildProfileByStudentRow, error) {
	row := q.db.QueryRow(ctx, getLatestWholeChildProfileByStudent, studentID)
	var i GetLatestWholeChildProfileByStudentRow
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.SchoolID,
		&i.ClassID,
		&i.AcademicYear,
		&i.Period,
		&i.AttendanceRatePct,
		&i.AcademicProfile,
		&i.PhysicalGrowthProfile,
		&i.HealthVisibilityProfile,
		&i.WellbeingProfile,
		&i.SocialCitizenshipProfile,
		&i.SyncSource,
		&i.SyncRecordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StudentName,
		&i.StudentEmail,
		&i.StudentDid,
	)
	return i, err
}

const getOfflineSyncBatchByChecksum = `-- name: GetOfflineSyncBatchByChecksum :one
SELECT id, batch_checksum, school_id, class_id, teacher_id, period, protocol_version, total_students, raw_payload, sync_method, synced_at FROM offline_sync_batches
WHERE batch_checksum = $1
`

func (q *Queries) GetOfflineSyncBatchByChecksum(ctx context.Context, batchChecksum string) (OfflineSyncBatch, error) {
	row := q.db.QueryRow(ctx, getOfflineSyncBatchByChecksum, batchChecksum)
	var i OfflineSyncBatch
	err := row.Scan(
		&i.ID,
		&i.BatchChecksum,
		&i.SchoolID,
		&i.ClassID,
		&i.TeacherID,
		&i.Period,
		&i.ProtocolVersion,
		&i.TotalStudents,
		&i.RawPayload,
		&i.SyncMethod,
		&i.SyncedAt,
	)
	return i, err
}

const getWholeChildProfileByStudentAndPeriod = `-- name: GetWholeChildProfileByStudentAndPeriod :one
SELECT 
    wcp.id, wcp.student_id, wcp.school_id, wcp.class_id, wcp.academic_year, wcp.period, wcp.attendance_rate_pct, wcp.academic_profile, wcp.physical_growth_profile, wcp.health_visibility_profile, wcp.wellbeing_profile, wcp.social_citizenship_profile, wcp.sync_source, wcp.sync_record_hash, wcp.created_at, wcp.updated_at,
    u.full_name AS student_name,
    u.email AS student_email,
    u.did AS student_did
FROM whole_child_profiles wcp
JOIN users u ON u.id = wcp.student_id
WHERE wcp.student_id = $1 AND wcp.period = $2
`

type GetWholeChildProfileByStudentAndPeriodParams struct {
	StudentID uuid.UUID `json:"student_id"`
	Period    string    `json:"period"`
}

type GetWholeChildProfileByStudentAndPeriodRow struct {
	ID                       uuid.UUID          `json:"id"`
	StudentID                uuid.UUID          `json:"student_id"`
	SchoolID                 uuid.UUID          `json:"school_id"`
	ClassID                  uuid.UUID          `json:"class_id"`
	AcademicYear             string             `json:"academic_year"`
	Period                   string             `json:"period"`
	AttendanceRatePct        pgtype.Numeric     `json:"attendance_rate_pct"`
	AcademicProfile          []byte             `json:"academic_profile"`
	PhysicalGrowthProfile    []byte             `json:"physical_growth_profile"`
	HealthVisibilityProfile  []byte             `json:"health_visibility_profile"`
	WellbeingProfile         []byte             `json:"wellbeing_profile"`
	SocialCitizenshipProfile []byte             `json:"social_citizenship_profile"`
	SyncSource               pgtype.Text        `json:"sync_source"`
	SyncRecordHash           pgtype.Text        `json:"sync_record_hash"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	StudentName              string             `json:"student_name"`
	StudentEmail             string             `json:"student_email"`
	StudentDid               pgtype.Text        `json:"student_did"`
}

func (q *Queries) GetWholeChildProfileByStudentAndPeriod(ctx context.Context, arg GetWholeChildProfileByStudentAndPeriodParams) (GetWholeChildProfileByStudentAndPeriodRow, error) {
	row := q.db.QueryRow(ctx, getWholeChildProfileByStudentAndPeriod, arg.StudentID, arg.Period)
	var i GetWholeChildProfileByStudentAndPeriodRow
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.SchoolID,
		&i.ClassID,
		&i.AcademicYear,
		&i.Period,
		&i.AttendanceRatePct,
		&i.AcademicProfile,
		&i.PhysicalGrowthProfile,
		&i.HealthVisibilityProfile,
		&i.WellbeingProfile,
		&i.SocialCitizenshipProfile,
		&i.SyncSource,
		&i.SyncRecordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StudentName,
		&i.StudentEmail,
		&i.StudentDid,
	)
	return i, err
}

const listOfflineSyncBatchesBySchool = `-- name: ListOfflineSyncBatchesBySchool :many
SELECT id, batch_checksum, school_id, class_id, teacher_id, period, protocol_version, total_students, raw_payload, sync_method, synced_at FROM offline_sync_batches
WHERE school_id = $1
ORDER BY synced_at DESC
LIMIT $2 OFFSET $3
`

type ListOfflineSyncBatchesBySchoolParams struct {
	SchoolID uuid.UUID `json:"school_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListOfflineSyncBatchesBySchool(ctx context.Context, arg ListOfflineSyncBatchesBySchoolParams) ([]OfflineSyncBatch, error) {
	rows, err := q.db.Query(ctx, listOfflineSyncBatchesBySchool, arg.SchoolID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OfflineSyncBatch{}
	for rows.Next() {
		var i OfflineSyncBatch
		if err := rows.Scan(
			&i.ID,
			&i.BatchChecksum,
			&i.SchoolID,
			&i.ClassID,
			&i.TeacherID,
			&i.Period,
			&i.ProtocolVersion,
			&i.TotalStudents,
			&i.RawPayload,
			&i.SyncMethod,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWholeChildProfilesByClassAndPeriod = `-- name: ListWholeChildProfilesByClassAndPeriod :many
SELECT 
    wcp.id, wcp.student_id, wcp.school_id, wcp.class_id, wcp.academic_year, wcp.period, wcp.attendance_rate_pct, wcp.academic_profile, wcp.physical_growth_profile, wcp.health_visibility_profile, wcp.wellbeing_profile, wcp.social_citizenship_profile, wcp.sync_source, wcp.sync_record_hash, wcp.created_at, wcp.updated_at,
    u.full_name AS student_name,
    u.email AS student_email,
    u.did AS student_did
FROM whole_child_profiles wcp
JOIN users u ON u.id = wcp.student_id
WHERE wcp.class_id = $1 AND wcp.period = $2
ORDER BY u.full_name ASC
`

type ListWholeChildProfilesByClassAndPeriodParams struct {
	ClassID uuid.UUID `json:"class_id"`
	Period  string    `json:"period"`
}

type ListWholeChildProfilesByClassAndPeriodRow struct {
	ID                       uuid.UUID          `json:"id"`
	StudentID                uuid.UUID          `json:"student_id"`
	SchoolID                 uuid.UUID          `json:"school_id"`
	ClassID                  uuid.UUID          `json:"class_id"`
	AcademicYear             string             `json:"academic_year"`
	Period                   string             `json:"period"`
	AttendanceRatePct        pgtype.Numeric     `json:"attendance_rate_pct"`
	AcademicProfile          []byte             `json:"academic_profile"`
	PhysicalGrowthProfile    []byte             `json:"physical_growth_profile"`
	HealthVisibilityProfile  []byte             `json:"health_visibility_profile"`
	WellbeingProfile         []byte             `json:"wellbeing_profile"`
	SocialCitizenshipProfile []byte             `json:"social_citizenship_profile"`
	SyncSource               pgtype.Text        `json:"sync_source"`
	SyncRecordHash           pgtype.Text        `json:"sync_record_hash"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	StudentName              string             `json:"student_name"`
	StudentEmail             string             `json:"student_email"`
	StudentDid               pgtype.Text        `json:"student_did"`
}

func (q *Queries) ListWholeChildProfilesByClassAndPeriod(ctx context.Context, arg ListWholeChildProfilesByClassAndPeriodParams) ([]ListWholeChildProfilesByClassAndPeriodRow, error) {
	rows, err := q.db.Query(ctx, listWholeChildProfilesByClassAndPeriod, arg.ClassID, arg.Period)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWholeChildProfilesByClassAndPeriodRow{}
	for rows.Next() {
		var i ListWholeChildProfilesByClassAndPeriodRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.SchoolID,
			&i.ClassID,
			&i.AcademicYear,
			&i.Period,
			&i.AttendanceRatePct,
			&i.AcademicProfile,
			&i.PhysicalGrowthProfile,
			&i.HealthVisibilityProfile,
			&i.WellbeingProfile,
			&i.SocialCitizenshipProfile,
			&i.SyncSource,
			&i.SyncRecordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StudentName,
			&i.StudentEmail,
			&i.StudentDid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWholeChildProfile = `-- name: UpsertWholeChildProfile :one
INSERT INTO whole_child_profiles (
    student_id,
    school_id,
    class_id,
    academic_year,
    period,
    attendance_rate_pct,
    academic_profile,
    physical_growth_profile,
    health_visibility_profile,
    wellbeing_profile,
    social_citizenship_profile,
    sync_source,
    sync_record_hash,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, NOW()
)
ON CONFLICT (student_id, period) DO UPDATE
SET 
    school_id = EXCLUDED.school_id,
    class_id = EXCLUDED.class_id,
    academic_year = EXCLUDED.academic_year,
    attendance_rate_pct = EXCLUDED.attendance_rate_pct,
    academic_profile = EXCLUDED.academic_profile,
    physical_growth_profile = EXCLUDED.physical_growth_profile,
    health_visibility_profile = EXCLUDED.health_visibility_profile,
    wellbeing_profile = EXCLUDED.wellbeing_profile,
    social_citizenship_profile = EXCLUDED.social_citizenship_profile,
    sync_source = EXCLUDED.sync_source,
    sync_record_hash = EXCLUDED.sync_record_hash,
    updated_at = NOW()
RETURNING id, student_id, school_id, class_id, academic_year, period, attendance_rate_pct, academic_profile, physical_growth_profile, health_visibility_profile, wellbeing_profile, social_citizenship_profile, sync_source, sync_record_hash, created_at, updated_at
`

type UpsertWholeChildProfileParams struct {
	StudentID                uuid.UUID      `json:"student_id"`
	SchoolID                 uuid.UUID      `json:"school_id"`
	ClassID                  uuid.UUID      `json:"class_id"`
	AcademicYear             string         `json:"academic_year"`
	Period                   string         `json:"period"`
	AttendanceRatePct        pgtype.Numeric `json:"attendance_rate_pct"`
	AcademicProfile          []byte         `json:"academic_profile"`
	PhysicalGrowthProfile    []byte         `json:"physical_growth_profile"`
	HealthVisibilityProfile  []byte         `json:"health_visibility_profile"`
	WellbeingProfile         []byte         `json:"wellbeing_profile"`
	SocialCitizenshipProfile []byte         `json:"social_citizenship_profile"`
	SyncSource               pgtype.Text    `json:"sync_source"`
	SyncRecordHash           pgtype.Text    `json:"sync_record_hash"`
}

func (q *Queries) UpsertWholeChildProfile(ctx context.Context, arg UpsertWholeChildProfileParams) (WholeChildProfile, error) {
	row := q.db.QueryRow(ctx, upsertWholeChildProfile,
		arg.StudentID,
		arg.SchoolID,
		arg.ClassID,
		arg.AcademicYear,
		arg.Period,
		arg.AttendanceRatePct,
		arg.AcademicProfile,
		arg.PhysicalGrowthProfile,
		arg.HealthVisibilityProfile,
		arg.WellbeingProfile,
		arg.SocialCitizenshipProfile,
		arg.SyncSource,
		arg.SyncRecordHash,
	)
	var i WholeChildProfile
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.SchoolID,
		&i.ClassID,
		&i.AcademicYear,
		&i.Period,
		&i.AttendanceRatePct,
		&i.AcademicProfile,
		&i.PhysicalGrowthProfile,
		&i.HealthVisibilityProfile,
		&i.WellbeingProfile,
		&i.SocialCitizenshipProfile,
		&i.SyncSource,
		&i.SyncRecordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
